/**
 * Dedicated listing pages at /listings/[slug].
 * Facts are as published by Hedgerow Exclusive Properties at hedgerowexclusive.com, with status cross-checked against
 * Zillow and MyStateMLS on 2026-10-08. Photos courtesy of Hedgerow Exclusive Properties.
 */

export type ListingStatus = "For sale" | "In contract";

export interface ListingPage {
  slug: string;
  address: string;
  area: string;
  zip: string;
  price: number;
  status: ListingStatus;
  beds?: string;
  baths?: string;
  sqft?: string;
  acres?: string;
  yearBuilt?: string;
  type: "SingleFamilyResidence" | "Land" | "Compound";
  headline: string;
  description: string[];
  highlights: string[];
  images: string[];
  hedgerowUrl: string;
}

export const LISTINGS_VERIFIED = "2026-10-08";

export const listingPages: ListingPage[] = [
  {
    slug: "70-71-cobb-lane-water-mill",
    address: "70 & 71 Cobb Lane",
    area: "Water Mill",
    zip: "11976",
    price: 82500000,
    status: "For sale",
    beds: "24",
    baths: "27 full, 11 half",
    sqft: "45,000",
    acres: "21+",
    type: "Compound",
    headline: "A Mecox Bay compound of two estates",
    description: ["Two neighboring estates on a private peninsula in Water Mill South, offered together for the first time. Across more than 21 acres on Burnett Creek, with a private dock and access to Mecox Bay, the compound pairs a 17,173 square foot Barnes Coy residence with a 28,000 square foot house built for entertaining.", "Between them are 24 bedrooms, two outdoor pools, tennis, an indoor pool and spa, a two-lane bowling alley and a 14-seat theater."],
    highlights: ["More than 3,100 feet of private shoreline on Burnett Creek", "Private dock with access to Mecox Bay", "Two residences totaling about 45,000 square feet", "Indoor pool, spa, sauna and steam", "Tennis court and two-level pool house", "11 garage spaces"],
    images: ["/images/listings/70-71-cobb-lane-water-mill/01.webp", "/images/listings/70-71-cobb-lane-water-mill/02.webp", "/images/listings/70-71-cobb-lane-water-mill/03.webp", "/images/listings/70-71-cobb-lane-water-mill/04.webp", "/images/listings/70-71-cobb-lane-water-mill/05.webp", "/images/listings/70-71-cobb-lane-water-mill/06.webp", "/images/listings/70-71-cobb-lane-water-mill/07.webp", "/images/listings/70-71-cobb-lane-water-mill/08.webp"],
    hedgerowUrl: "https://hedgerowexclusive.com/listings/70-71-cobb-lane-water-mill-ny-11976/",
  },
  {
    slug: "70-cobb-lane-water-mill",
    address: "70 Cobb Lane",
    area: "Water Mill",
    zip: "11976",
    price: 42500000,
    status: "For sale",
    beds: "11",
    baths: "14 full, 5 half",
    sqft: "28,000",
    acres: "12.2",
    type: "SingleFamilyResidence",
    headline: "An entertaining estate on Mecox Bay",
    description: ["A 12.2 acre estate on a private peninsula on Mecox Bay, with 28,000 square feet of living space across three levels. The upper floors hold a primary suite, guest bedrooms and terraces with views toward the bay.", "The lower level is given over to a 14-seat theater, a two-lane bowling alley, half-court basketball, a professional gym and an indoor pool and spa. Outside are a heated gunite pool with waterfall and spa, a cabana and an attached three-car garage."],
    highlights: ["Private peninsula setting on Mecox Bay", "14-seat theater and two-lane bowling alley", "Indoor pool, spa, sauna and steam room", "350-bottle wine cellar", "Heated gunite pool with waterfall and spa", "Attached three-car garage"],
    images: ["/images/listings/70-cobb-lane-water-mill/01.webp", "/images/listings/70-cobb-lane-water-mill/02.webp", "/images/listings/70-cobb-lane-water-mill/03.webp", "/images/listings/70-cobb-lane-water-mill/04.webp", "/images/listings/70-cobb-lane-water-mill/05.webp", "/images/listings/70-cobb-lane-water-mill/06.webp", "/images/listings/70-cobb-lane-water-mill/07.webp", "/images/listings/70-cobb-lane-water-mill/08.webp"],
    hedgerowUrl: "https://hedgerowexclusive.com/listings/70-cobb-lane-water-mill-ny-11976/",
  },
  {
    slug: "71-cobb-lane-water-mill",
    address: "71 Cobb Lane",
    area: "Water Mill",
    zip: "11976",
    price: 39950000,
    status: "For sale",
    beds: "13",
    baths: "13 full, 6 half",
    sqft: "17,173",
    acres: "9",
    type: "SingleFamilyResidence",
    headline: "A Barnes Coy estate on Burnett Creek",
    description: ["Designed by Barnes Coy Architects and updated continuously over two decades, this 17,173 square foot residence sits on more than nine acres with over 3,100 feet of private shoreline on Burnett Creek. Bay views run through the principal rooms, and there are 13 bedrooms plus staff quarters.", "The grounds include tennis, a saltwater gunite pool and spa, a two-level pool house with a commercial kitchen and gym, and a path down to a private dock."],
    highlights: ["Over 3,100 feet of shoreline on Burnett Creek", "Private dock with access to Mecox Bay", "Saltwater gunite pool, spa and sauna", "Tennis court with tennis house", "Two-level pool house with commercial kitchen", "Eight garage spaces"],
    images: ["/images/listings/71-cobb-lane-water-mill/01.webp", "/images/listings/71-cobb-lane-water-mill/02.webp", "/images/listings/71-cobb-lane-water-mill/03.webp", "/images/listings/71-cobb-lane-water-mill/04.webp", "/images/listings/71-cobb-lane-water-mill/05.webp", "/images/listings/71-cobb-lane-water-mill/06.webp", "/images/listings/71-cobb-lane-water-mill/07.webp", "/images/listings/71-cobb-lane-water-mill/08.webp"],
    hedgerowUrl: "https://hedgerowexclusive.com/listings/71-cobb-lane-water-mill-ny-11976/",
  },
  {
    slug: "1880-meadow-lane-southampton",
    address: "1880 Meadow Lane",
    area: "Southampton",
    zip: "11968",
    price: 28000000,
    status: "For sale",
    acres: "3.4",
    type: "Land",
    headline: "Oceanfront land on Meadow Lane",
    description: ["About 3.4 acres with 200 feet of ocean frontage on Meadow Lane in Southampton Village, with views from the Atlantic across to Shinnecock Bay.", "Offered as a vacant parcel, the site has the potential for a residence of approximately 15,000 square feet with an oceanside pool and a tennis court. Few parcels on Meadow Lane combine this much land with this much frontage."],
    highlights: ["200 feet of ocean frontage", "Approximately 3.4 acres in Southampton Village", "Ocean and bay views", "Potential for a residence of about 15,000 square feet", "Room for an oceanside pool and tennis"],
    images: ["/images/listings/1880-meadow-lane-southampton/01.webp", "/images/listings/1880-meadow-lane-southampton/02.webp", "/images/listings/1880-meadow-lane-southampton/03.webp", "/images/listings/1880-meadow-lane-southampton/04.webp", "/images/listings/1880-meadow-lane-southampton/07.webp", "/images/listings/1880-meadow-lane-southampton/08.webp"],
    hedgerowUrl: "https://hedgerowexclusive.com/listings/1880-meadow-lane-southampton-ny-11968/",
  },
  {
    slug: "14-st-marys-lane-amagansett",
    address: "14 St Mary's Lane",
    area: "Amagansett",
    zip: "11930",
    price: 19950000,
    status: "For sale",
    beds: "7",
    baths: "8 full, 1 half",
    sqft: "9,000",
    acres: "1.9",
    type: "SingleFamilyResidence",
    headline: "A French-inspired house with ocean views",
    description: ["A French-inspired residence in Amagansett with ocean views, seven bedrooms and about 9,000 square feet on 1.9 acres. The living room rises to a double-height ceiling with hand-hewn beams around a limestone fireplace, and the kitchen is by Clive Christian.", "Outside, a south-facing travertine terrace of nearly 3,000 square feet leads to a saltwater pool and spa, a summer kitchen and a pool house."],
    highlights: ["Clive Christian kitchen", "Double-height living room with French limestone fireplace", "Steam room, sauna and media room", "Nearly 3,000 square feet of travertine terrace", "Saltwater pool with cascading spa", "Pool house with kitchenette and full bath"],
    images: ["/images/listings/14-st-marys-lane-amagansett/01.webp", "/images/listings/14-st-marys-lane-amagansett/02.webp", "/images/listings/14-st-marys-lane-amagansett/03.webp", "/images/listings/14-st-marys-lane-amagansett/04.webp", "/images/listings/14-st-marys-lane-amagansett/05.webp", "/images/listings/14-st-marys-lane-amagansett/06.webp", "/images/listings/14-st-marys-lane-amagansett/07.webp", "/images/listings/14-st-marys-lane-amagansett/08.webp"],
    hedgerowUrl: "https://hedgerowexclusive.com/listings/14-st-marys-lane-amagansett-ny-11930/",
  },
  {
    slug: "351-jobs-lane-bridgehampton",
    address: "351 Jobs Lane",
    area: "Bridgehampton",
    zip: "11932",
    price: 9650000,
    status: "In contract",
    acres: "1.43",
    type: "Land",
    headline: "Level land south of the highway",
    description: ["A level 1.43 acre parcel south of the highway in Bridgehampton, framed by hedgerows and moments from the ocean beaches and the village.", "Conceptual plans show a principal residence of approximately 8,000 square feet over two levels, with a detached garage, pool and pool house, and a full-size tennis court."],
    highlights: ["1.43 level acres south of the highway", "Conceptual plans for about 8,000 square feet", "Room for pool, pool house and tennis", "Moments from ocean beaches and the village"],
    images: ["/images/listings/351-jobs-lane-bridgehampton/01.webp", "/images/listings/351-jobs-lane-bridgehampton/02.webp", "/images/listings/351-jobs-lane-bridgehampton/04.webp", "/images/listings/351-jobs-lane-bridgehampton/05.webp", "/images/listings/351-jobs-lane-bridgehampton/06.webp"],
    hedgerowUrl: "https://hedgerowexclusive.com/listings/351-jobs-lane-bridgehampton-ny-11932/",
  },
  {
    slug: "60-two-holes-of-water-road-east-hampton",
    address: "60 Two Holes of Water Road",
    area: "East Hampton",
    zip: "11937",
    price: 8995000,
    status: "In contract",
    beds: "8",
    baths: "10 full, 3 half",
    sqft: "12,000",
    acres: "3.1",
    yearBuilt: "2025",
    type: "SingleFamilyResidence",
    headline: "New construction on three acres",
    description: ["A newly completed cedar shake residence on 3.1 acres in East Hampton's Village Fringe, privately sited at the end of a long drive. Nearly 12,000 square feet across three levels hold eight bedrooms and an amenity level made for year-round living.", "Mature perimeter hedging, specimen trees and a north-south orientation give the grounds the feel of a private resort."],
    highlights: ["Completed in 2025", "3.1 acres at the end of a long private drive", "Double-height entry foyer", "Amenity lower level", "Landscape architecture with specimen trees"],
    images: ["/images/listings/60-two-holes-of-water-road-east-hampton/01.webp", "/images/listings/60-two-holes-of-water-road-east-hampton/02.webp", "/images/listings/60-two-holes-of-water-road-east-hampton/03.webp", "/images/listings/60-two-holes-of-water-road-east-hampton/04.webp", "/images/listings/60-two-holes-of-water-road-east-hampton/05.webp", "/images/listings/60-two-holes-of-water-road-east-hampton/06.webp", "/images/listings/60-two-holes-of-water-road-east-hampton/07.webp", "/images/listings/60-two-holes-of-water-road-east-hampton/08.webp"],
    hedgerowUrl: "https://hedgerowexclusive.com/listings/60-two-holes-of-water-road-east-hampton-ny-11937/",
  },
  {
    slug: "58-cove-hollow-road-east-hampton",
    address: "58 Cove Hollow Road",
    area: "East Hampton",
    zip: "11937",
    price: 7995000,
    status: "For sale",
    beds: "6",
    baths: "6 full, 2 half",
    sqft: "6,421",
    acres: "0.51",
    yearBuilt: "2023",
    type: "SingleFamilyResidence",
    headline: "A modern farmhouse near the village",
    description: ["A modern farmhouse completed in 2023, set on Cove Hollow Road a few minutes from East Hampton Village. Its 6,421 square feet run across three finished levels, from a great room under a two-story vaulted ceiling to a lower level with a gym, media room and wet bar.", "Six bedrooms include a main-level primary suite with French doors to the heated gunite pool and lawn."],
    highlights: ["Great room with two-story vaulted ceiling", "Chef's kitchen with wine storage", "Main-level primary suite", "Lower level with gym, media and game rooms", "Heated gunite pool"],
    images: ["/images/listings/58-cove-hollow-road-east-hampton/01.webp", "/images/listings/58-cove-hollow-road-east-hampton/02.webp", "/images/listings/58-cove-hollow-road-east-hampton/03.webp", "/images/listings/58-cove-hollow-road-east-hampton/04.webp", "/images/listings/58-cove-hollow-road-east-hampton/05.webp", "/images/listings/58-cove-hollow-road-east-hampton/06.webp", "/images/listings/58-cove-hollow-road-east-hampton/07.webp", "/images/listings/58-cove-hollow-road-east-hampton/08.webp"],
    hedgerowUrl: "https://hedgerowexclusive.com/listings/58-cove-hollow-road-east-hampton-ny-11937/",
  },
  {
    slug: "8-margarets-drive-shelter-island",
    address: "8 Margaret's Drive",
    area: "Shelter Island",
    zip: "11964",
    price: 6395000,
    status: "For sale",
    beds: "5",
    baths: "6 full, 1 half",
    sqft: "4,250",
    acres: "1.05",
    yearBuilt: "2026",
    type: "SingleFamilyResidence",
    headline: "New construction on West Neck Creek",
    description: ["New waterfront construction on 1.05 acres with direct frontage on West Neck Creek, built by Mark Lumley Contracting with architecture by London Architecture + Design.", "About 4,250 square feet, including an office and full bath above the detached garage, are finished in wide-plank white oak around a Sub-Zero and Wolf kitchen. Mahogany decking leads to a 15 by 48 foot saltwater gunite pool facing the creek."],
    highlights: ["Direct frontage on West Neck Creek", "Newly built in 2026", "Sub-Zero, Wolf and Cove kitchen", "Office and full bath above the garage", "15 by 48 foot saltwater gunite pool"],
    images: ["/images/listings/8-margarets-drive-shelter-island/01.webp", "/images/listings/8-margarets-drive-shelter-island/02.webp", "/images/listings/8-margarets-drive-shelter-island/03.webp", "/images/listings/8-margarets-drive-shelter-island/04.webp", "/images/listings/8-margarets-drive-shelter-island/05.webp", "/images/listings/8-margarets-drive-shelter-island/06.webp", "/images/listings/8-margarets-drive-shelter-island/07.webp"],
    hedgerowUrl: "https://hedgerowexclusive.com/listings/8-margarets-drive-shelter-island-ny-11964/",
  },
  {
    slug: "20-prospect-avenue-shelter-island",
    address: "20 Prospect Avenue",
    area: "Shelter Island",
    zip: "11965",
    price: 4995000,
    status: "For sale",
    beds: "7",
    baths: "6",
    sqft: "5,000",
    acres: "1.2",
    yearBuilt: "1883",
    type: "SingleFamilyResidence",
    headline: "Aquarelle, on Divinity Hill",
    description: ["Aquarelle, built in 1883, is one of the original houses on Divinity Hill in Shelter Island Heights, now a national historic district. The 5,000 square foot residence keeps its broad covered porch, with seven bedrooms and bay views on 1.2 acres.", "A 40 by 20 foot pool, beach access and a detached two-car garage complete the property."],
    highlights: ["Built in 1883 in a national historic district", "Waterfront with bay views", "Wide covered porch", "40 by 20 foot pool", "Beach access", "Detached two-car garage"],
    images: ["/images/listings/20-prospect-avenue-shelter-island/01.webp", "/images/listings/20-prospect-avenue-shelter-island/02.webp", "/images/listings/20-prospect-avenue-shelter-island/03.webp", "/images/listings/20-prospect-avenue-shelter-island/04.webp", "/images/listings/20-prospect-avenue-shelter-island/05.webp", "/images/listings/20-prospect-avenue-shelter-island/06.webp", "/images/listings/20-prospect-avenue-shelter-island/07.webp", "/images/listings/20-prospect-avenue-shelter-island/08.webp"],
    hedgerowUrl: "https://hedgerowexclusive.com/listings/20-prospect-avenue-shelter-island-ny-11965/",
  },
  {
    slug: "73-oyster-shores-road-east-hampton",
    address: "73 Oyster Shores Road",
    area: "East Hampton",
    zip: "11937",
    price: 4950000,
    status: "For sale",
    beds: "5",
    baths: "5 full, 1 half",
    sqft: "3,000",
    acres: "0.6",
    type: "SingleFamilyResidence",
    headline: "A renovated contemporary above the bay",
    description: ["A 1970s contemporary in Northwest Woods, renovated to new construction standards, on an elevated site of about 0.6 acres with bay views and deeded access to Three Mile Harbor across the street.", "Inside are mid-century dome ceilings, a double-sided fireplace and a Sub-Zero kitchen with a travertine waterfall island, along with a theater and gym, a dry sauna and a wine room. Outside, a new heated gunite pool, an outdoor kitchen and a wraparound balcony."],
    highlights: ["Deeded access to Three Mile Harbor", "Bay views from an elevated site", "Two primary suites with heated floors", "Theater, gym, sauna and wine room", "New heated gunite pool and outdoor kitchen"],
    images: ["/images/listings/73-oyster-shores-road-east-hampton/01.webp", "/images/listings/73-oyster-shores-road-east-hampton/02.webp", "/images/listings/73-oyster-shores-road-east-hampton/03.webp", "/images/listings/73-oyster-shores-road-east-hampton/04.webp", "/images/listings/73-oyster-shores-road-east-hampton/05.webp", "/images/listings/73-oyster-shores-road-east-hampton/06.webp", "/images/listings/73-oyster-shores-road-east-hampton/07.webp", "/images/listings/73-oyster-shores-road-east-hampton/08.webp"],
    hedgerowUrl: "https://hedgerowexclusive.com/listings/73-oyster-shores-road-east-hampton-ny-11937/",
  },
  {
    slug: "15-edgemere-street-montauk",
    address: "15 Edgemere Street",
    area: "Montauk",
    zip: "11954",
    price: 4699000,
    status: "For sale",
    beds: "4",
    baths: "4",
    sqft: "2,400",
    acres: "1",
    yearBuilt: "2006",
    type: "SingleFamilyResidence",
    headline: "Sunsets over the water in Montauk",
    description: ["A traditional house on a private, elevated acre in Montauk, with sunsets over the water and the primary suite looking out to the view.", "Inside are an eat-in kitchen with a large island, a living room with fireplace and bedrooms with their own baths, and a patio with hot tub opens off the main floor. A full basement and room for a pool round out a move-in ready property near town, the ocean and the harbor."],
    highlights: ["Elevated, private acre", "Water views and western sunsets", "Primary suite with water views", "Patio with hot tub", "Room to add a pool"],
    images: ["/images/listings/15-edgemere-street-montauk/01.webp", "/images/listings/15-edgemere-street-montauk/02.webp", "/images/listings/15-edgemere-street-montauk/03.webp", "/images/listings/15-edgemere-street-montauk/04.webp", "/images/listings/15-edgemere-street-montauk/05.webp", "/images/listings/15-edgemere-street-montauk/06.webp", "/images/listings/15-edgemere-street-montauk/07.webp", "/images/listings/15-edgemere-street-montauk/08.webp"],
    hedgerowUrl: "https://hedgerowexclusive.com/listings/15-edgemere-street-montauk-ny-11954/",
  },
  {
    slug: "113-sebonac-road-southampton",
    address: "113 Sebonac Road",
    area: "Southampton",
    zip: "11968",
    price: 3895000,
    status: "For sale",
    beds: "5",
    baths: "5 full, 1 half",
    sqft: "4,085",
    acres: "0.76",
    yearBuilt: "2017",
    type: "SingleFamilyResidence",
    headline: "On the fairways of Southampton Golf Club",
    description: ["A 2017 traditional on 0.76 acres in Southampton, overlooking the fairways of Southampton Golf Club. Five bedrooms include a first-floor primary suite, with a chef's kitchen, a dining room that seats twelve and a finished lower level with a media room and wet bar.", "An 18 by 40 foot heated gunite pool sits off two patios, and the attached two-car garage has an EV charger."],
    highlights: ["Overlooks Southampton Golf Club", "First-floor primary suite", "Two fireplaces", "Finished lower level with media room", "18 by 40 foot heated gunite pool"],
    images: ["/images/listings/113-sebonac-road-southampton/01.webp", "/images/listings/113-sebonac-road-southampton/02.webp", "/images/listings/113-sebonac-road-southampton/03.webp", "/images/listings/113-sebonac-road-southampton/04.webp", "/images/listings/113-sebonac-road-southampton/05.webp", "/images/listings/113-sebonac-road-southampton/06.webp", "/images/listings/113-sebonac-road-southampton/07.webp", "/images/listings/113-sebonac-road-southampton/08.webp"],
    hedgerowUrl: "https://hedgerowexclusive.com/listings/113-sebonac-road-southampton-ny-11968/",
  },
  {
    slug: "568-old-sag-harbor-road-bridgehampton",
    address: "568 Old Sag Harbor Road",
    area: "Bridgehampton",
    zip: "11932",
    price: 3550000,
    status: "For sale",
    beds: "4",
    baths: "4 full, 1 half",
    sqft: "3,777",
    acres: "3.3",
    yearBuilt: "1997",
    type: "SingleFamilyResidence",
    headline: "Three private acres in Bridgehampton",
    description: ["A traditional residence at the end of a private drive on 3.3 acres, central to Bridgehampton, Sag Harbor and Southampton. Renovated in 2023, it has a double-height entry, four bedrooms including one on the first floor, and a renovated kitchen opening to a covered porch and patio.", "The grounds hold a 20 by 40 foot heated pool and spa, with room for a pickleball or padel court."],
    highlights: ["3.3 acres at the end of a private drive", "Renovated in 2023", "First-floor bedroom suite", "20 by 40 foot heated pool with spa", "Room for pickleball or padel"],
    images: ["/images/listings/568-old-sag-harbor-road-bridgehampton/01.webp", "/images/listings/568-old-sag-harbor-road-bridgehampton/02.webp", "/images/listings/568-old-sag-harbor-road-bridgehampton/03.webp", "/images/listings/568-old-sag-harbor-road-bridgehampton/04.webp", "/images/listings/568-old-sag-harbor-road-bridgehampton/05.webp", "/images/listings/568-old-sag-harbor-road-bridgehampton/06.webp", "/images/listings/568-old-sag-harbor-road-bridgehampton/07.webp", "/images/listings/568-old-sag-harbor-road-bridgehampton/08.webp"],
    hedgerowUrl: "https://hedgerowexclusive.com/listings/568-old-sag-harbor-road-bridgehampton-ny-11932/",
  },
  {
    slug: "51-little-noyack-path-water-mill",
    address: "51 Little Noyack Path",
    area: "Water Mill",
    zip: "11976",
    price: 3295000,
    status: "In contract",
    beds: "3",
    baths: "3",
    sqft: "2,500",
    acres: "1.1",
    type: "SingleFamilyResidence",
    headline: "A renovated retreat on 1.1 acres",
    description: ["A traditional house on 1.1 acres in Water Mill, renovated in 2024 with a clean, modern interior. The great room centers on a fireplace and opens through floor-to-ceiling doors to mahogany decks, stone patios and mature gardens.", "The primary suite occupies its own upper level, with a private balcony over the pool."],
    highlights: ["Renovated in 2024", "Great room with fireplace", "Separate office or den", "Primary suite with private balcony", "Mahogany decking and stone patios"],
    images: ["/images/listings/51-little-noyack-path-water-mill/01.webp", "/images/listings/51-little-noyack-path-water-mill/02.webp", "/images/listings/51-little-noyack-path-water-mill/03.webp", "/images/listings/51-little-noyack-path-water-mill/04.webp", "/images/listings/51-little-noyack-path-water-mill/05.webp", "/images/listings/51-little-noyack-path-water-mill/06.webp", "/images/listings/51-little-noyack-path-water-mill/07.webp", "/images/listings/51-little-noyack-path-water-mill/08.webp"],
    hedgerowUrl: "https://hedgerowexclusive.com/listings/51-little-noyack-path-water-mill-ny-11976/",
  },
  {
    slug: "106-laurel-drive-montauk",
    address: "106 Laurel Drive",
    area: "Montauk",
    zip: "11954",
    price: 1495000,
    status: "For sale",
    acres: "0.94",
    type: "Land",
    headline: "Land in Hither Hills",
    description: ["Close to an acre in Montauk's Hither Hills, on an elevated lot south of the highway and minutes from the beaches and the village.", "The parcel offers room for a new residence with a pool and outdoor space, subject to zoning and approvals."],
    highlights: ["0.94 acres in Hither Hills", "Elevated site south of the highway", "Minutes from beaches and the village"],
    images: ["/images/listings/106-laurel-drive-montauk/01.webp", "/images/listings/106-laurel-drive-montauk/02.webp", "/images/listings/106-laurel-drive-montauk/03.webp"],
    hedgerowUrl: "https://hedgerowexclusive.com/listings/106-laurel-drive-montauk-ny-11954/",
  },
];

export const listingBySlug = (slug: string) => listingPages.find((l) => l.slug === slug);

/** Hedgerow listing URL to internal listing page, for linking /sales cards. */
export const listingPathByHedgerowUrl: Record<string, string> = Object.fromEntries(listingPages.map((l) => [l.hedgerowUrl, `/listings/${l.slug}`]));

export const formatPrice = (n: number) => `$${n.toLocaleString("en-US")}`;
