export interface Listing {
  address: string;
  area: string;
  slug: string;
  price: string;
  priceNum: number;
  beds?: string;
  baths?: string;
  sqft?: string;
  acres?: string;
  description: string;
  image: string;
  listingUrl: string;
  isLand?: boolean;
}

export const activeListings: Listing[] = [
  {
    address: "70 & 71 Cobb Lane",
    area: "Water Mill",
    slug: "70-71-cobb-lane",
    price: "$99,500,000",
    priceNum: 99500000,
    beds: "24",
    baths: "27F 11H",
    sqft: "45,000",
    acres: "21.00",
    description: "Available for the first time, this extremely rare waterfront compound spans over 21 total acres with Mecox Bay access.",
    image: "/images/listings/70-71-cobb-lane.jpg",
    listingUrl: "https://hedgerowexclusive.com/listings/70-71-cobb-lane-water-mill-ny-11976/",
  },
  {
    address: "70 Cobb Lane",
    area: "Water Mill",
    slug: "70-cobb-lane",
    price: "$54,950,000",
    priceNum: 54950000,
    beds: "11",
    baths: "14F 5H",
    sqft: "28,000",
    acres: "12.20",
    description: "Set on a private peninsula on Mecox Bay, this stunning 12.2 acre estate presents 28,000 square feet of living space across three levels with resort-style living.",
    image: "/images/listings/70-cobb-lane.jpg",
    listingUrl: "https://hedgerowexclusive.com/listings/70-cobb-lane-water-mill-ny-11976/",
  },
  {
    address: "71 Cobb Lane",
    area: "Water Mill",
    slug: "71-cobb-lane",
    price: "$44,500,000",
    priceNum: 44500000,
    beds: "13",
    baths: "13F 6H",
    sqft: "17,173",
    acres: "9.11",
    description: "Located along a private peninsula on Mecox Bay, the property presents the ultimate in setting and exclusivity.",
    image: "/images/listings/71-cobb-lane.jpg",
    listingUrl: "https://hedgerowexclusive.com/listings/71-cobb-lane-water-mill-ny-11976/",
  },
  {
    address: "448 Further Lane",
    area: "East Hampton",
    slug: "448-further-lane",
    price: "$32,500,000",
    priceNum: 32500000,
    beds: "6",
    baths: "8.5",
    sqft: "6,200",
    acres: "1.06",
    description: "This immaculate, super private, Further Lane estate was designed and built by AD-100 firm, Fox-Nahem Associates.",
    image: "/images/listings/448-further-lane.jpg",
    listingUrl: "https://hedgerowexclusive.com/listings/448-further-lane-east-hampton-ny-11937/",
  },
  {
    address: "104 Quimby Lane",
    area: "Bridgehampton",
    slug: "104-quimby-lane",
    price: "$27,500,000",
    priceNum: 27500000,
    beds: "8",
    baths: "10F 2H",
    sqft: "12,500",
    acres: "3.07",
    description: "A masterfully executed estate on one of Bridgehampton's most sought-after lanes, this south-of-the-highway retreat spans over 3 acres.",
    image: "/images/listings/104-quimby-lane.jpg",
    listingUrl: "https://hedgerowexclusive.com/listings/104-quimby-lane-bridgehampton-ny-11932/",
  },
  {
    address: "104 Georgica Close Road",
    area: "East Hampton",
    slug: "104-georgica-close",
    price: "$24,500,000",
    priceNum: 24500000,
    beds: "7",
    baths: "8F 2H",
    sqft: "7,000",
    acres: "2.00",
    description: "Set on 2 acres on Georgica Pond, this new construction waterfront estate features over 300 feet of water frontage.",
    image: "/images/listings/104-georgica-close.jpg",
    listingUrl: "https://hedgerowexclusive.com/listings/104-georgica-close-road-east-hampton-ny-11937/",
  },
  {
    address: "14 St Mary's Lane",
    area: "Amagansett",
    slug: "14-st-marys-lane",
    price: "$19,950,000",
    priceNum: 19950000,
    beds: "7",
    baths: "8.5",
    sqft: "9,000",
    acres: "1.90",
    description: "A rare blend of timeless elegance and modern indulgence, this French-inspired retreat is a home that resonates with both artistry and comfort.",
    image: "/images/listings/14-st-marys-lane.jpg",
    listingUrl: "https://hedgerowexclusive.com/listings/14-st-marys-lane-amagansett-ny-11930/",
  },
  {
    address: "40 Deforest Road",
    area: "Montauk",
    slug: "40-deforest-road",
    price: "$17,495,000",
    priceNum: 17495000,
    beds: "6",
    baths: "5.5",
    sqft: "4,800",
    acres: "1.00",
    description: "Set on a sprawling 1 acre parcel with 95 feet of ocean frontage, Casa Las Olas stands as the quintessence of opulent coastal living.",
    image: "/images/listings/40-deforest-road.jpg",
    listingUrl: "https://hedgerowexclusive.com/listings/40-deforest-road-montauk-ny-11954/",
  },
  {
    address: "207 Madison Street",
    area: "Sag Harbor",
    slug: "207-madison-street",
    price: "$14,750,000",
    priceNum: 14750000,
    beds: "5",
    baths: "6F 2H",
    sqft: "5,000",
    acres: "0.38",
    description: "Set in the heart of Sag Harbor Village, 207 Madison Street stands as both a work of architecture and a living chronicle of local history.",
    image: "/images/listings/207-madison-street.jpg",
    listingUrl: "https://hedgerowexclusive.com/listings/207-madison-street-sag-harbor-ny-11963/",
  },
  {
    address: "946 Ocean Road",
    area: "Bridgehampton",
    slug: "946-ocean-road",
    price: "$12,750,000",
    priceNum: 12750000,
    acres: "3.00",
    description: "Set on 3 acres and surrounded by mature specimen trees, this property offers both immediate enjoyment and future potential.",
    image: "/images/listings/946-ocean-road.jpg",
    listingUrl: "https://hedgerowexclusive.com/listings/946-ocean-road-bridgehampton-ny-11932/",
    isLand: true,
  },
  {
    address: "1076 Ocean Road",
    area: "Bridgehampton",
    slug: "1076-ocean-road",
    price: "$11,995,000",
    priceNum: 11995000,
    beds: "6",
    baths: "6.5",
    sqft: "5,000",
    acres: "1.02",
    description: "This 1.02-acre haven redefines waterfront living, where luxury meets functionality in this six-bedroom sanctuary.",
    image: "/images/listings/1076-ocean-road.jpg",
    listingUrl: "https://hedgerowexclusive.com/listings/1076-ocean-road-bridgehampton-2/",
  },
  {
    address: "60 Two Holes of Water Road",
    area: "East Hampton",
    slug: "60-two-holes",
    price: "$10,995,000",
    priceNum: 10995000,
    beds: "8",
    baths: "10F 3H",
    sqft: "12,000",
    acres: "3.10",
    description: "Just completed in East Hampton's Village Fringe, this newly built estate represents a rare convergence of architectural refinement and three acres of curated natural beauty.",
    image: "/images/listings/60-two-holes.jpg",
    listingUrl: "https://hedgerowexclusive.com/listings/60-two-holes-of-water-road-east-hampton-ny-11937/",
  },
  {
    address: "351 Jobs Lane",
    area: "Bridgehampton",
    slug: "351-jobs-lane",
    price: "$9,950,000",
    priceNum: 9950000,
    acres: "1.45",
    description: "Prime south-of-the-highway land opportunity on one of Bridgehampton's most prestigious lanes.",
    image: "/images/listings/351-jobs-lane.jpg",
    listingUrl: "https://hedgerowexclusive.com/listings/351-jobs-lane-bridgehampton-ny-11932/",
    isLand: true,
  },
  {
    address: "16 & 18 Wills Point Road",
    area: "Montauk",
    slug: "16-18-wills-point",
    price: "$9,495,000",
    priceNum: 9495000,
    beds: "5",
    baths: "8.5",
    acres: "2.53",
    description: "An extraordinary compound opportunity encompassing two waterfront parcels in Montauk's coveted Wills Point neighborhood.",
    image: "/images/listings/16-18-wills-point.jpg",
    listingUrl: "https://hedgerowexclusive.com/listings/16-18-wills-point-road-montauk-ny-11954/",
  },
  {
    address: "134 Second House Road",
    area: "Montauk",
    slug: "134-second-house",
    price: "$8,000,000",
    priceNum: 8000000,
    beds: "3",
    baths: "2",
    acres: "4.43",
    description: "A rare 4.43 acre parcel on Second House Road offering exceptional development potential in the heart of Montauk.",
    image: "/images/listings/134-second-house.jpg",
    listingUrl: "https://hedgerowexclusive.com/listings/134-second-house-road-montauk-ny-11954/",
  },
  {
    address: "1694 Millstone Road",
    area: "Sag Harbor",
    slug: "1694-millstone",
    price: "$7,850,000",
    priceNum: 7850000,
    beds: "7",
    baths: "7F 3H",
    sqft: "9,000",
    acres: "1.85",
    description: "Set for completion August 2025, where modern sophistication meets timeless European elegance on nearly 2 acres.",
    image: "/images/listings/1694-millstone.jpg",
    listingUrl: "https://hedgerowexclusive.com/listings/1694-millstone-road-sag-harbor-ny-11963/",
  },
  {
    address: "16 Wills Point Road",
    area: "Montauk",
    slug: "16-wills-point",
    price: "$6,995,000",
    priceNum: 6995000,
    beds: "5",
    baths: "8.5",
    sqft: "6,000",
    acres: "1.38",
    description: "A stunning waterfront property in Montauk's sought-after Wills Point neighborhood with panoramic water views.",
    image: "/images/listings/16-wills-point.jpg",
    listingUrl: "https://hedgerowexclusive.com/listings/16-wills-point-road-montauk-ny-11954/",
  },
  {
    address: "2749 Montauk Highway",
    area: "Bridgehampton",
    slug: "2749-montauk-hwy",
    price: "$5,495,000",
    priceNum: 5495000,
    beds: "4",
    baths: "3.5",
    acres: "0.82",
    description: "A charming Bridgehampton property situated on Montauk Highway with excellent visibility and location.",
    image: "/images/listings/2749-montauk-hwy.jpg",
    listingUrl: "https://hedgerowexclusive.com/listings/2749-montauk-highway-bridgehampton-ny-11932/",
  },
  {
    address: "20 Prospect Avenue",
    area: "Shelter Island Heights",
    slug: "20-prospect-ave",
    price: "$4,995,000",
    priceNum: 4995000,
    beds: "7",
    baths: "6",
    sqft: "5,000",
    acres: "1.20",
    description: "An iconic piece of Shelter Island Heights history, this distinguished waterfront home offers an extraordinary opportunity.",
    image: "/images/listings/20-prospect-ave.jpg",
    listingUrl: "https://hedgerowexclusive.com/listings/20-prospect-avenue-shelter-island-ny-11965/",
  },
  {
    address: "21 Cove Road",
    area: "Sag Harbor",
    slug: "21-cove-road",
    price: "$4,450,000",
    priceNum: 4450000,
    beds: "4",
    baths: "3.5",
    sqft: "3,000",
    acres: "0.20",
    description: "Located in the Redwood waterfront community of Sag Harbor Village, this architect-designed home has been completely renovated.",
    image: "/images/listings/21-cove-road.jpg",
    listingUrl: "https://hedgerowexclusive.com/listings/21-cove-road-sag-harbor-ny-11963/",
  },
  {
    address: "5 Grand Avenue",
    area: "Shelter Island Heights",
    slug: "5-grand-ave",
    price: "$2,150,000",
    priceNum: 2150000,
    beds: "3",
    baths: "3",
    sqft: "2,000",
    acres: "0.24",
    description: "An extraordinary multi-use opportunity completed in 2024, nestled in the Historic Business District of Shelter Island Heights.",
    image: "/images/listings/5-grand-ave.jpg",
    listingUrl: "https://hedgerowexclusive.com/listings/5-grand-avenue-shelter-island-ny-11965/",
  },
  {
    address: "17 Maidstone Park Road",
    area: "East Hampton",
    slug: "17-maidstone-park",
    price: "$1,965,000",
    priceNum: 1965000,
    beds: "4",
    baths: "3",
    sqft: "2,500",
    acres: "0.33",
    description: "Experience the charm of East Hampton in this luxurious home, ideally located 0.2 miles from Maidstone Park Beach.",
    image: "/images/listings/17-maidstone-park.jpg",
    listingUrl: "https://hedgerowexclusive.com/listings/17-maidstone-park-road-east-hampton-ny-11937/",
  },
];

export const totalPortfolioValue = activeListings.reduce((sum, l) => sum + l.priceNum, 0);
export const formattedPortfolioValue = `$${Math.round(totalPortfolioValue / 1000000)}M+`;
