export interface Listing {
  address: string;
  area: string;
  slug: string;
  price: string;
  priceNum: number;
  status: string;
  beds?: string;
  baths?: string;
  sqft?: string;
  acres?: string;
  description: string;
  image: string;
  listingUrl: string;
  isLand?: boolean;
}

export const activeListings: Listing[] = [
{
    address: "70 & 71 Cobb Lane",
    area: "Water Mill",
    slug: "70-71-cobb-lane-water-mill",
    price: "$82,500,000",
    priceNum: 82500000,
    status: "For Sale",
    beds: "24",
    baths: "27F 11H",
    sqft: "45,000",
    acres: "21.00",
    description: "Water Mill compound offering, 70 & 71 Cobb Lane combined.",
    image: "/images/listings/70-71-cobb-lane.jpg",
    listingUrl: "https://hedgerow.eastendli.com/property/910536/",
  },
{
    address: "70 Cobb Lane",
    area: "Water Mill",
    slug: "70-cobb-lane-water-mill",
    price: "$42,500,000",
    priceNum: 42500000,
    status: "For Sale",
    beds: "11",
    baths: "14F 5H",
    sqft: "28,000",
    acres: "12.20",
    description: "Water Mill estate on 12.2 acres at 70 Cobb Lane.",
    image: "/images/listings/70-cobb-lane.jpg",
    listingUrl: "https://hedgerow.eastendli.com/property/899290/",
  },
{
    address: "71 Cobb Lane",
    area: "Water Mill",
    slug: "71-cobb-lane-water-mill",
    price: "$39,950,000",
    priceNum: 39950000,
    status: "For Sale",
    beds: "13",
    baths: "13F 6H",
    sqft: "17,173",
    acres: "9.11",
    description: "Water Mill estate on 9.11 acres at 71 Cobb Lane.",
    image: "/images/listings/71-cobb-lane.jpg",
    listingUrl: "https://hedgerow.eastendli.com/property/888739/",
  },
{
    address: "582 & 598 Halsey Lane",
    area: "Bridgehampton",
    slug: "582-598-halsey-lane-bridgehampton",
    price: "$38,900,000",
    priceNum: 38900000,
    status: "For Sale",
    beds: "9",
    baths: "9F 2H",
    sqft: "11,000",
    acres: "3.00",
    description:
      "Bridgehampton South new-construction compound opportunity on nearly three acres across two adjacent lots.",
    image: "/images/listings/582-598-halsey-lane.jpg",
    listingUrl: "https://hedgerow.eastendli.com/property/935228/",
  },
{
    address: "14 St Mary's Lane",
    area: "Amagansett",
    slug: "14-st-marys-lane-amagansett",
    price: "$19,950,000",
    priceNum: 19950000,
    status: "For Sale",
    beds: "7",
    baths: "8.5",
    sqft: "9,000",
    acres: "1.90",
    description: "Amagansett residence on nearly two acres at 14 St Mary's Lane.",
    image: "/images/listings/14-st-marys-lane.jpg",
    listingUrl: "https://hedgerow.eastendli.com/property/925935/",
  },
{
    address: "36 Oakland Avenue",
    area: "Sag Harbor",
    slug: "36-oakland-avenue-sag-harbor",
    price: "$12,650,000",
    priceNum: 12650000,
    status: "For Sale",
    beds: "6",
    baths: "6.5",
    sqft: "6,000",
    acres: "0.54",
    description:
      "Western-facing Sag Harbor Village waterfront on Otter Cove, newly constructed with sunset water views.",
    image: "/images/listings/36-oakland-avenue.jpg",
    listingUrl: "https://hedgerow.eastendli.com/property/934260/",
  },
{
    address: "351 Jobs Lane",
    area: "Bridgehampton",
    slug: "351-jobs-lane-bridgehampton-active",
    price: "$9,650,000",
    priceNum: 9650000,
    status: "In Contract",
    acres: "1.43",
    description:
      "Rare development opportunity south of the highway, with 1.43 level acres moments from ocean beaches.",
    image: "/images/listings/351-jobs-lane-active.jpg",
    listingUrl: "https://hedgerow.eastendli.com/property/932217/",
    isLand: true,
  },
{
    address: "60 Two Holes of Water Road",
    area: "East Hampton",
    slug: "60-two-holes-east-hampton-active",
    price: "$8,995,000",
    priceNum: 8995000,
    status: "In Contract",
    beds: "8",
    baths: "10F 3H",
    sqft: "12,000",
    acres: "3.10",
    description:
      "Just-completed East Hampton Village Fringe estate with tennis on three curated acres.",
    image: "/images/listings/60-two-holes-active.jpg",
    listingUrl: "https://hedgerow.eastendli.com/property/927793/",
  },
{
    address: "58 Cove Hollow Road",
    area: "East Hampton",
    slug: "58-cove-hollow-east-hampton",
    price: "$7,995,000",
    priceNum: 7995000,
    status: "For Sale",
    beds: "6",
    baths: "6F 2H",
    sqft: "6,421",
    acres: "0.51",
    description: "East Hampton residence on Cove Hollow Road, with six bedrooms on just over half an acre.",
    image: "/images/listings/58-cove-hollow.jpg",
    listingUrl: "https://hedgerow.eastendli.com/property/935517/",
  },
{
    address: "33 Dinah Rock Road",
    area: "Shelter Island",
    slug: "33-dinah-rock-shelter-island",
    price: "$6,995,000",
    priceNum: 6995000,
    status: "In Contract",
    beds: "6",
    baths: "4",
    sqft: "4,875",
    acres: "2.10",
    description:
      "Rare west-facing waterfront estate with private beachfront and dock with 186 feet of natural beach.",
    image: "/images/listings/33-dinah-rock.jpg",
    listingUrl: "https://hedgerow.eastendli.com/property/930613/",
  },
{
    address: "20 Prospect Avenue",
    area: "Shelter Island Heights",
    slug: "20-prospect-avenue-shelter-island",
    price: "$4,995,000",
    priceNum: 4995000,
    status: "For Sale",
    beds: "7",
    baths: "6",
    sqft: "5,000",
    acres: "1.20",
    description: "Shelter Island Heights residence on 1.2 acres at 20 Prospect Avenue.",
    image: "/images/listings/20-prospect-ave.jpg",
    listingUrl: "https://hedgerow.eastendli.com/property/908849/",
  },
{
    address: "2 Hilltop Lane",
    area: "East Hampton",
    slug: "2-hilltop-lane-east-hampton",
    price: "$3,995,000",
    priceNum: 3995000,
    status: "For Sale",
    beds: "6",
    baths: "5",
    sqft: "5,247",
    acres: "1.46",
    description:
      "Recently renovated East Hampton retreat with tennis on 1.46 private acres.",
    image: "/images/listings/2-hilltop-lane.jpg",
    listingUrl: "https://hedgerow.eastendli.com/property/934942/",
  },
{
    address: "568 Old Sag Harbor Road",
    area: "Bridgehampton",
    slug: "568-old-sag-harbor-bridgehampton",
    price: "$3,695,000",
    priceNum: 3695000,
    status: "For Sale",
    beds: "4",
    baths: "4.5",
    sqft: "3,777",
    acres: "3.30",
    description:
      "Turnkey traditional on 3.3 private acres in Bridgehampton with room for pickleball or padel.",
    image: "/images/listings/568-old-sag-harbor.jpg",
    listingUrl: "https://hedgerow.eastendli.com/property/932626/",
  },
];

export const totalPortfolioValue = activeListings
  .filter((l) => l.status !== "For Rent")
  .reduce((sum, l) => sum + l.priceNum, 0);
