/**
 * Portfolio data cross-referenced with hedgerowexclusive.com (public listings and prominent deals),
 * recorded deeds, press, and Barry's records. Generated 2026-10-07; see
 * drafts/homes/portfolio-work for the build scripts and source notes.
 * Roles are Hedgerow Exclusive Properties' (the firm's) role as published by the firm, never a personal side.
 */

export type HedgerowGroup = "Oceanfront" | "Waterfront" | "Estate and village";

export interface HedgerowActiveListing {
  address: string;
  area: string;
  price: string;
  priceNum: number;
  status: "For sale" | "In contract";
  beds: string;
  baths: string;
  sqft: string;
  acres: string;
  description: string;
  image: string;
  alt: string;
  listingUrl: string;
}

export interface HedgerowSoldDeal {
  address: string;
  area: string;
  price: string;
  priceNum: number;
  date: string;
  dateText: string;
  /** Hedgerow Exclusive Properties' role (firm), as published by Hedgerow or documented in the cited record. */
  hedgerowRole: string;
  /** Hedgerow's role in Hedgerow's own words from its Prominent Deals page, e.g. "Hedgerow represented the seller"; otherwise "A Hedgerow transaction". */
  roleLabel?: string;
  group: HedgerowGroup;
  barryInvolved?: boolean;
  image?: string;
  alt?: string;
}

export const HEDGEROW_SOURCE_NOTE =
  "Listing details, prices, and roles as published by Hedgerow Exclusive Properties at hedgerowexclusive.com, cross-checked against recorded deeds and press.";

export const hedgerowActiveListings: HedgerowActiveListing[] = [
  {
    "address": "70 & 71 Cobb Lane",
    "area": "Water Mill",
    "price": "$82,500,000",
    "priceNum": 82500000,
    "status": "For sale",
    "beds": "24",
    "baths": "27F 11H",
    "sqft": "45,000",
    "acres": "24",
    "description": "Available for the first time, this extremely rare waterfront compound spans over 21 total acres with Mecox Bay access.",
    "image": "/images/hedgerow/active-70-71-cobb-lane-water-mill.webp",
    "alt": "70 & 71 Cobb Lane, Water Mill. Photo courtesy of Hedgerow Exclusive Properties",
    "listingUrl": "https://hedgerowexclusive.com/listings/70-71-cobb-lane-water-mill-ny-11976/"
  },
  {
    "address": "70 Cobb Lane",
    "area": "Water Mill",
    "price": "$42,500,000",
    "priceNum": 42500000,
    "status": "For sale",
    "beds": "11",
    "baths": "14F 5H",
    "sqft": "28,000",
    "acres": "12.20",
    "description": "Set on a private peninsula on Mecox Bay, this stunning 12.2 +/- acre estate presents 28,000 +/- square feet of living space across three levels with resort-style living.",
    "image": "/images/hedgerow/active-70-cobb-lane-water-mill.webp",
    "alt": "70 Cobb Lane, Water Mill. Photo courtesy of Hedgerow Exclusive Properties",
    "listingUrl": "https://hedgerowexclusive.com/listings/70-cobb-lane-water-mill-ny-11976/"
  },
  {
    "address": "71 Cobb Lane",
    "area": "Water Mill",
    "price": "$39,950,000",
    "priceNum": 39950000,
    "status": "For sale",
    "beds": "13",
    "baths": "13F 6H",
    "sqft": "17,173",
    "acres": "9",
    "description": "Located along a private peninsula on Mecox Bay, the property presents the ultimate in setting and exclusivity.",
    "image": "/images/hedgerow/active-71-cobb-lane-water-mill.webp",
    "alt": "71 Cobb Lane, Water Mill. Photo courtesy of Hedgerow Exclusive Properties",
    "listingUrl": "https://hedgerowexclusive.com/listings/71-cobb-lane-water-mill-ny-11976/"
  },
  {
    "address": "1880 Meadow Lane",
    "area": "Southampton",
    "price": "$28,000,000",
    "priceNum": 28000000,
    "status": "For sale",
    "beds": "",
    "baths": "",
    "sqft": "",
    "acres": "3.4",
    "description": "Set along one of the most coveted stretches of oceanfront in the Hamptons, 1880 Meadow Lane presents an extraordinary opportunity to create a significant new estate on approximately 3.4 acres with 200 feet of pristine ocean frontage.",
    "image": "/images/hedgerow/active-1880-meadow-lane-southampton.webp",
    "alt": "1880 Meadow Lane, Southampton. Photo courtesy of Hedgerow Exclusive Properties",
    "listingUrl": "https://hedgerowexclusive.com/listings/1880-meadow-lane-southampton-ny-11968/"
  },
  {
    "address": "14 St Mary's Lane",
    "area": "Amagansett",
    "price": "$19,950,000",
    "priceNum": 19950000,
    "status": "For sale",
    "beds": "7",
    "baths": "8F & 1H",
    "sqft": "9,000",
    "acres": "1.90",
    "description": "A rare blend of timeless elegance and modern indulgence, this French-inspired East Hampton retreat is a home that resonates with both artistry and comfort.",
    "image": "/images/hedgerow/active-14-st-marys-lane-amagansett.webp",
    "alt": "14 St Mary's Lane, Amagansett. Photo courtesy of Hedgerow Exclusive Properties",
    "listingUrl": "https://hedgerowexclusive.com/listings/14-st-marys-lane-amagansett-ny-11930/"
  },
  {
    "address": "351 Jobs Lane",
    "area": "Bridgehampton",
    "price": "$9,650,000",
    "priceNum": 9650000,
    "status": "In contract",
    "beds": "",
    "baths": "",
    "sqft": "",
    "acres": "1.43",
    "description": "Tucked between hedgerows on a coveted stretch south of the highway, 351 Jobs Lane offers something the Hamptons rarely yields anymore - a level, generous 1.43 ± acre parcel of unbuilt land, just moments from ocean beaches and the village.",
    "image": "/images/hedgerow/active-351-jobs-lane-bridgehampton.webp",
    "alt": "351 Jobs Lane, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties",
    "listingUrl": "https://hedgerowexclusive.com/listings/351-jobs-lane-bridgehampton-ny-11932/"
  },
  {
    "address": "60 Two Holes of Water Road",
    "area": "East Hampton",
    "price": "$8,995,000",
    "priceNum": 8995000,
    "status": "In contract",
    "beds": "8",
    "baths": "10F 3H",
    "sqft": "12,000",
    "acres": "3.10",
    "description": "Just completed in East Hampton’s Village Fringe, this newly built estate represents a rare convergence of architectural refinement, modern comfort, and three acres of curated natural beauty.",
    "image": "/images/hedgerow/active-60-two-holes-of-water-road-east-hampton.webp",
    "alt": "60 Two Holes of Water Road, East Hampton. Photo courtesy of Hedgerow Exclusive Properties",
    "listingUrl": "https://hedgerowexclusive.com/listings/60-two-holes-of-water-road-east-hampton-ny-11937/"
  },
  {
    "address": "58 Cove Hollow Road",
    "area": "East Hampton",
    "price": "$7,995,000",
    "priceNum": 7995000,
    "status": "For sale",
    "beds": "6",
    "baths": "6F & 2H",
    "sqft": "6,421",
    "acres": "0.51",
    "description": "Set along Cove Hollow Road just moments from East Hampton Village, this beautifully designed modern farmhouse pairs generous proportions with a private setting close to the shops, restaurants, and beaches that define East Hampton living.",
    "image": "/images/hedgerow/active-58-cove-hollow-road-east-hampton.webp",
    "alt": "58 Cove Hollow Road, East Hampton. Photo courtesy of Hedgerow Exclusive Properties",
    "listingUrl": "https://hedgerowexclusive.com/listings/58-cove-hollow-road-east-hampton-ny-11937/"
  },
  {
    "address": "8 Margaret's Drive",
    "area": "Shelter Island",
    "price": "$6,395,000",
    "priceNum": 6395000,
    "status": "For sale",
    "beds": "5",
    "baths": "6F & 1H",
    "sqft": "4,250",
    "acres": "1.05",
    "description": "Set on 1.05± acres along the shores of West Neck Creek, 8 Margaret’s Drive presents a newly constructed waterfront residence designed to embrace the natural beauty and relaxed character of Shelter Island.",
    "image": "/images/hedgerow/active-8-margarets-drive-shelter-island.webp",
    "alt": "8 Margaret's Drive, Shelter Island. Photo courtesy of Hedgerow Exclusive Properties",
    "listingUrl": "https://hedgerowexclusive.com/listings/8-margarets-drive-shelter-island-ny-11964/"
  },
  {
    "address": "20 Prospect Avenue",
    "area": "Shelter Island",
    "price": "$4,995,000",
    "priceNum": 4995000,
    "status": "For sale",
    "beds": "7",
    "baths": "6",
    "sqft": "5,000",
    "acres": "1.2",
    "description": "An iconic piece of Shelter Island Heights history, this distinguished waterfront home offers an extraordinary opportunity for the discerning buyer.",
    "image": "/images/hedgerow/active-20-prospect-avenue-shelter-island.webp",
    "alt": "20 Prospect Avenue, Shelter Island. Photo courtesy of Hedgerow Exclusive Properties",
    "listingUrl": "https://hedgerowexclusive.com/listings/20-prospect-avenue-shelter-island-ny-11965/"
  },
  {
    "address": "73 Oyster Shores Road",
    "area": "East Hampton",
    "price": "$4,950,000",
    "priceNum": 4950000,
    "status": "For sale",
    "beds": "5",
    "baths": "5F & 1H",
    "sqft": "3,000",
    "acres": "",
    "description": "Discover 73 Oyster Shores Road, East Hampton, NY 11937 Set on approximately 0.6 acres in the desirable Northwest Woods, this landmark 1970s contemporary home has been fully renovated to new construction standards. The approximately 3,000 square-foot residence offers five bedrooms and five full and one half bathrooms on an elevated site with sweeping bay views […]",
    "image": "/images/hedgerow/active-73-oyster-shores-road-east-hampton.webp",
    "alt": "73 Oyster Shores Road, East Hampton. Photo courtesy of Hedgerow Exclusive Properties",
    "listingUrl": "https://hedgerowexclusive.com/listings/73-oyster-shores-road-east-hampton-ny-11937/"
  },
  {
    "address": "15 Edgemere Street",
    "area": "Montauk",
    "price": "$4,699,000",
    "priceNum": 4699000,
    "status": "For sale",
    "beds": "4",
    "baths": "4",
    "sqft": "2,400",
    "acres": "1",
    "description": "Discover 15 Edgemere Street, Montauk, NY 11954 Sweeping sunsets over the Long Island Sound are a defining feature of this beautifully maintained traditional home. Tucked away on a private, elevated acre, the residence is move-in ready and spans roughly 2,500 square feet of thoughtfully designed living space. Inside, you’ll find rich dark hardwood floors, refined […]",
    "image": "/images/hedgerow/active-15-edgemere-street-montauk.webp",
    "alt": "15 Edgemere Street, Montauk. Photo courtesy of Hedgerow Exclusive Properties",
    "listingUrl": "https://hedgerowexclusive.com/listings/15-edgemere-street-montauk-ny-11954/"
  },
  {
    "address": "113 Sebonac Road",
    "area": "Southampton",
    "price": "$3,895,000",
    "priceNum": 3895000,
    "status": "For sale",
    "beds": "5",
    "baths": "5F & 1H",
    "sqft": "4,085",
    "acres": "0.76",
    "description": "Discover this charming traditional home situated on a spacious .74-acre lot in prime Southampton.",
    "image": "/images/hedgerow/active-113-sebonac-road-southampton.webp",
    "alt": "113 Sebonac Road, Southampton. Photo courtesy of Hedgerow Exclusive Properties",
    "listingUrl": "https://hedgerowexclusive.com/listings/113-sebonac-road-southampton-ny-11968/"
  },
  {
    "address": "568 Old Sag Harbor Road",
    "area": "Bridgehampton",
    "price": "$3,550,000",
    "priceNum": 3550000,
    "status": "For sale",
    "beds": "4",
    "baths": "4F & 1H",
    "sqft": "3,777",
    "acres": "3.3",
    "description": "Discover 568 Old Sag Harbor Road, Bridgehampton, NY 11963 Set at the end of a private driveway on 3.3 acres in Bridgehampton, this beautifully maintained traditional Hamptons residence offers approximately 4,000 square feet of timeless living space designed for comfort, entertaining, and year-round enjoyment. The home features a dramatic double-story entryway, four bedrooms including a […]",
    "image": "/images/hedgerow/active-568-old-sag-harbor-road-bridgehampton.webp",
    "alt": "568 Old Sag Harbor Road, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties",
    "listingUrl": "https://hedgerowexclusive.com/listings/568-old-sag-harbor-road-bridgehampton-ny-11932/"
  },
  {
    "address": "51 Little Noyack Path",
    "area": "Water Mill",
    "price": "$3,295,000",
    "priceNum": 3295000,
    "status": "In contract",
    "beds": "3",
    "baths": "3",
    "sqft": "2,500",
    "acres": "1.1",
    "description": "Secluded and serene on 1.1 lush acres in Water Mill, this timeless 3 bedroom, 3 bath traditional home, thoughtfully renovated in 2024, blends classic Hamptons charm with a sleek, modern interior aesthetic.",
    "image": "/images/hedgerow/active-51-little-noyack-path-water-mill.webp",
    "alt": "51 Little Noyack Path, Water Mill. Photo courtesy of Hedgerow Exclusive Properties",
    "listingUrl": "https://hedgerowexclusive.com/listings/51-little-noyack-path-water-mill-ny-11976/"
  },
  {
    "address": "106 Laurel Drive",
    "area": "Montauk",
    "price": "$1,495,000",
    "priceNum": 1495000,
    "status": "For sale",
    "beds": "",
    "baths": "",
    "sqft": "",
    "acres": "0.94",
    "description": "Set in Montauk’s desirable Hither Hills neighborhood, 106 Laurel Drive presents a rare opportunity to create a custom retreat on 0.95± acre.",
    "image": "/images/hedgerow/active-106-laurel-drive-montauk.webp",
    "alt": "106 Laurel Drive, Montauk. Photo courtesy of Hedgerow Exclusive Properties",
    "listingUrl": "https://hedgerowexclusive.com/listings/106-laurel-drive-montauk-ny-11954/"
  }
];

/** Sold 2021 to 2026, newest first. */
export const hedgerowSold2021: HedgerowSoldDeal[] = [
  {
    "address": "33 Dinah Rock Road",
    "area": "Shelter Island",
    "price": "$6,995,000",
    "priceNum": 6995000,
    "date": "2026-09-25",
    "dateText": "Sep 2026",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": true,
    "image": "/images/hedgerow/sold-33-dinah-rock-road-shelter-island-2026.webp",
    "alt": "33 Dinah Rock Road, Shelter Island. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the buyer"
  },
  {
    "address": "40 Deforest Road",
    "area": "Montauk",
    "price": "",
    "priceNum": 0,
    "date": "2026-09",
    "dateText": "2026",
    "hedgerowRole": "Co-listing",
    "group": "Oceanfront",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-40-deforest-road-montauk-2026.webp",
    "alt": "40 Deforest Road (Casa Las Olas), Montauk. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "A Hedgerow transaction"
  },
  {
    "address": "1694 Millstone Road",
    "area": "Sag Harbor",
    "price": "$6,095,000",
    "priceNum": 6095000,
    "date": "2026-06-25",
    "dateText": "Jun 2026",
    "hedgerowRole": "Co-listing",
    "group": "Estate and village",
    "barryInvolved": true,
    "image": "",
    "alt": "",
    "roleLabel": "A Hedgerow transaction"
  },
  {
    "address": "5 Grand Avenue",
    "area": "Shelter Island",
    "price": "$1,999,999",
    "priceNum": 1999999,
    "date": "2026-06-18",
    "dateText": "Jun 2026",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": true,
    "image": "/images/hedgerow/sold-5-grand-avenue-shelter-island-2026.webp",
    "alt": "5 Grand Avenue, Shelter Island. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "104 Quimby Lane",
    "area": "Bridgehampton",
    "price": "$22,150,000",
    "priceNum": 22150000,
    "date": "2026-04-28",
    "dateText": "Apr 2026",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-104-quimby-lane-bridgehampton-2026.webp",
    "alt": "104 Quimby Lane, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "946 Ocean Road",
    "area": "Bridgehampton",
    "price": "$10,300,000",
    "priceNum": 10300000,
    "date": "2026-04-24",
    "dateText": "Apr 2026",
    "hedgerowRole": "Both sides",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-946-ocean-road-bridgehampton-2026.webp",
    "alt": "946 Ocean Road, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented both sides"
  },
  {
    "address": "47B South Ferry Road",
    "area": "Shelter Island",
    "price": "$3,500,000",
    "priceNum": 3500000,
    "date": "2026-04-20",
    "dateText": "Apr 2026",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": true,
    "image": "/images/hedgerow/sold-47b-south-ferry-road-shelter-island-2026.webp",
    "alt": "47B South Ferry Road, Shelter Island. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "43 East Dune Lane",
    "area": "East Hampton",
    "price": "$72,000,000",
    "priceNum": 72000000,
    "date": "2026-03-06",
    "dateText": "Mar 2026",
    "hedgerowRole": "Co-listing",
    "group": "Oceanfront",
    "barryInvolved": true,
    "image": "",
    "alt": "",
    "roleLabel": "A Hedgerow transaction"
  },
  {
    "address": "11 South Harbor Drive",
    "area": "Sag Harbor",
    "price": "$6,450,000",
    "priceNum": 6450000,
    "date": "2026-02-25",
    "dateText": "Feb 2026",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-11-south-harbor-drive-sag-harbor-2026.webp",
    "alt": "11 South Harbor Drive, Sag Harbor. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "55 Dunes Lane",
    "area": "Amagansett",
    "price": "$43,500,000",
    "priceNum": 43500000,
    "date": "2026-02-04",
    "dateText": "Feb 2026",
    "hedgerowRole": "Listing",
    "group": "Oceanfront",
    "barryInvolved": true,
    "image": "/images/hedgerow/sold-55-dunes-lane-amagansett-2026.webp",
    "alt": "55 Dunes Lane, Amagansett. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "109 Duck Pond Lane",
    "area": "Southampton",
    "price": "$20,000,000",
    "priceNum": 20000000,
    "date": "2026-01-16",
    "dateText": "Jan 2026",
    "hedgerowRole": "Listing",
    "group": "Waterfront",
    "barryInvolved": true,
    "image": "/images/hedgerow/sold-109-duck-pond-lane-southampton-2026.webp",
    "alt": "109 Duck Pond Lane, Southampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "3 Pheasant Lane",
    "area": "East Hampton",
    "price": "$8,125,000",
    "priceNum": 8125000,
    "date": "2026-01-16",
    "dateText": "Jan 2026",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-3-pheasant-lane-east-hampton-2026.webp",
    "alt": "3 Pheasant Lane, East Hampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "14 Barns Lane",
    "area": "East Hampton",
    "price": "$2,025,000",
    "priceNum": 2025000,
    "date": "2025-12-17",
    "dateText": "Dec 2025",
    "hedgerowRole": "Both sides",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-14-barns-lane-east-hampton-2025.webp",
    "alt": "14 Barns Lane, East Hampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented both sides"
  },
  {
    "address": "225 Old Montauk Highway",
    "area": "Montauk",
    "price": "$10,500,000",
    "priceNum": 10500000,
    "date": "2025-12-15",
    "dateText": "Dec 2025",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-225-old-montauk-highway-montauk-2025.webp",
    "alt": "225 Old Montauk Highway, Montauk. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "2 Town Line Road",
    "area": "Sagaponack",
    "price": "$10,000,000",
    "priceNum": 10000000,
    "date": "2025-12-12",
    "dateText": "Dec 2025",
    "hedgerowRole": "Listing",
    "group": "Oceanfront",
    "barryInvolved": true,
    "image": "/images/hedgerow/sold-2-town-line-road-sagaponack-2025.webp",
    "alt": "2 Town Line Road, Sagaponack. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "144 Corrigan Street",
    "area": "Southampton",
    "price": "$7,237,500",
    "priceNum": 7237500,
    "date": "2025-11-21",
    "dateText": "Nov 2025",
    "hedgerowRole": "Both sides",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-144-corrigan-street-southampton-2025.webp",
    "alt": "144 Corrigan Street, Southampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented both sides"
  },
  {
    "address": "24 & 36 Jeffreys Lane",
    "area": "East Hampton",
    "price": "$36,250,000",
    "priceNum": 36250000,
    "date": "2025-11-18",
    "dateText": "Nov 2025",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-24-36-jeffreys-lane-east-hampton-2025.webp",
    "alt": "24 & 36 Jeffreys Lane, East Hampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "165 Surfside Drive",
    "area": "Bridgehampton",
    "price": "$58,000,000",
    "priceNum": 58000000,
    "date": "2025-11-14",
    "dateText": "Nov 2025",
    "hedgerowRole": "Advised buyer",
    "group": "Oceanfront",
    "barryInvolved": true,
    "image": "/images/hedgerow/sold-165-surfside-drive-bridgehampton-2025.webp",
    "alt": "165 Surfside Drive, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow advised the buyer"
  },
  {
    "address": "42 Deforest Road",
    "area": "Montauk",
    "price": "$17,000,000",
    "priceNum": 17000000,
    "date": "2025-11-12",
    "dateText": "Nov 2025",
    "hedgerowRole": "Co-listing",
    "group": "Oceanfront",
    "barryInvolved": false,
    "roleLabel": "A Hedgerow transaction"
  },
  {
    "address": "79 Surfside Drive",
    "area": "Bridgehampton",
    "price": "$28,000,000",
    "priceNum": 28000000,
    "date": "2025-11-05",
    "dateText": "Nov 2025",
    "hedgerowRole": "Both sides",
    "group": "Oceanfront",
    "barryInvolved": true,
    "image": "/images/hedgerow/sold-79-surfside-drive-bridgehampton-2025.webp",
    "alt": "79 Surfside Drive, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented both sides"
  },
  {
    "address": "36 Chase Court",
    "area": "Bridgehampton",
    "price": "$7,300,000",
    "priceNum": 7300000,
    "date": "2025-11-05",
    "dateText": "Nov 2025",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "barryInvolved": true,
    "image": "",
    "alt": "",
    "roleLabel": "A Hedgerow transaction"
  },
  {
    "address": "125 Mid Ocean Drive",
    "area": "Bridgehampton",
    "price": "$57,000,000",
    "priceNum": 57000000,
    "date": "2025-10-22",
    "dateText": "Oct 2025",
    "hedgerowRole": "Buyer side",
    "group": "Oceanfront",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-125-mid-ocean-drive-bridgehampton-2025.webp",
    "alt": "125 Mid Ocean Drive, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the buyer"
  },
  {
    "address": "10 Meadowbrook Way",
    "area": "Sag Harbor",
    "price": "$6,500,000",
    "priceNum": 6500000,
    "date": "2025-10-20",
    "dateText": "Oct 2025",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-10-meadowbrook-way-sag-harbor-2025.webp",
    "alt": "10 Meadowbrook Way, Sag Harbor. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the buyer"
  },
  {
    "address": "802 Town Line Road",
    "area": "Sagaponack",
    "price": "$26,350,000",
    "priceNum": 26350000,
    "date": "2025-10-09",
    "dateText": "Oct 2025",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-802-town-line-road-sagaponack-2025.webp",
    "alt": "802 Town Line Road, Sagaponack. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "36 Sagg Road",
    "area": "Sagaponack",
    "price": "$3,750,000",
    "priceNum": 3750000,
    "date": "2025-10-07",
    "dateText": "Oct 2025",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-36-sagg-road-sagaponack-2025.webp",
    "alt": "36 Sagg Road, Sagaponack. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the buyer"
  },
  {
    "address": "533 David Whites Lane",
    "area": "Southampton",
    "price": "$2,250,000",
    "priceNum": 2250000,
    "date": "2025-10-07",
    "dateText": "Oct 2025",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-533-david-whites-lane-southampton-2025.webp",
    "alt": "533 David Whites Lane, Southampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the buyer"
  },
  {
    "address": "36 Agnew Avenue",
    "area": "Montauk",
    "price": "$2,367,167",
    "priceNum": 2367167,
    "date": "2025-09-22",
    "dateText": "Sep 2025",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-36-agnew-avenue-montauk-2025.webp",
    "alt": "36 Agnew Avenue, Montauk. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the buyer"
  },
  {
    "address": "1 Pandion Road",
    "area": "Shelter Island",
    "price": "$12,850,000",
    "priceNum": 12850000,
    "date": "2025-09-11",
    "dateText": "Sep 2025",
    "hedgerowRole": "Listing",
    "group": "Waterfront",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-1-pandion-road-shelter-island-2025.webp",
    "alt": "1 Pandion Road, Shelter Island. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "A Hedgerow transaction"
  },
  {
    "address": "33 Lily Pond Lane",
    "area": "East Hampton",
    "price": "$31,500,000",
    "priceNum": 31500000,
    "date": "2025-09-05",
    "dateText": "Sep 2025",
    "hedgerowRole": "Listing",
    "group": "Oceanfront",
    "barryInvolved": true,
    "image": "/images/hedgerow/sold-33-lily-pond-lane-east-hampton-2025.webp",
    "alt": "33 Lily Pond Lane, East Hampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "7 Casey Lane",
    "area": "Bridgehampton",
    "price": "$3,760,000",
    "priceNum": 3760000,
    "date": "2025-06-12",
    "dateText": "Jun 2025",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-7-casey-lane-bridgehampton-2025.webp",
    "alt": "7 Casey Lane, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "83 Mount Misery Drive",
    "area": "Sag Harbor",
    "price": "$3,850,000",
    "priceNum": 3850000,
    "date": "2025-06-09",
    "dateText": "Jun 2025",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-83-mount-misery-drive-sag-harbor-2025.webp",
    "alt": "83 Mount Misery Drive, Sag Harbor. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "21 North Main Street",
    "area": "East Hampton",
    "price": "$6,000,000",
    "priceNum": 6000000,
    "date": "2025-06-04",
    "dateText": "Jun 2025",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-21-north-main-street-east-hampton-2025.webp",
    "alt": "21 North Main Street, East Hampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "24 Fort Pond Boulevard",
    "area": "East Hampton",
    "price": "$1,240,000",
    "priceNum": 1240000,
    "date": "2025-06-04",
    "dateText": "Jun 2025",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-24-fort-pond-boulevard-east-hampton-2025.webp",
    "alt": "24 Fort Pond Boulevard, East Hampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "120 Bay Lane",
    "area": "Water Mill",
    "price": "$12,625,000",
    "priceNum": 12625000,
    "date": "2025-05-29",
    "dateText": "May 2025",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-120-bay-lane-water-mill-2025.webp",
    "alt": "120 Bay Lane, Water Mill. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "12 Jackson Street",
    "area": "East Hampton",
    "price": "$1,985,000",
    "priceNum": 1985000,
    "date": "2025-04-15",
    "dateText": "Apr 2025",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-12-jackson-street-east-hampton-2025.webp",
    "alt": "12 Jackson Street, East Hampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "86 Skimhampton Road",
    "area": "East Hampton",
    "price": "$8,850,000",
    "priceNum": 8850000,
    "date": "2025-04-14",
    "dateText": "Apr 2025",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-86-skimhampton-road-east-hampton-2025.webp",
    "alt": "86 Skimhampton Road, East Hampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "26 Duke Drive",
    "area": "East Hampton",
    "price": "$6,350,000",
    "priceNum": 6350000,
    "date": "2025-04-11",
    "dateText": "Apr 2025",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-26-duke-drive-east-hampton-2025.webp",
    "alt": "26 Duke Drive, East Hampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "67 Surfside Drive",
    "area": "Bridgehampton",
    "price": "$32,000,000",
    "priceNum": 32000000,
    "date": "2025-04-04",
    "dateText": "Apr 2025",
    "hedgerowRole": "Both sides",
    "group": "Oceanfront",
    "barryInvolved": true,
    "image": "/images/hedgerow/sold-67-surfside-drive-bridgehampton-2025.webp",
    "alt": "67 Surfside Drive, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented both sides"
  },
  {
    "address": "10 Helens Lane",
    "area": "Southampton",
    "price": "$1,671,000",
    "priceNum": 1671000,
    "date": "2025-03-26",
    "dateText": "Mar 2025",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-10-helens-lane-southampton-2025.webp",
    "alt": "10 Helens Lane, Southampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the buyer"
  },
  {
    "address": "27 Winding Way",
    "area": "Water Mill",
    "price": "$6,000,000",
    "priceNum": 6000000,
    "date": "2025-03-07",
    "dateText": "Mar 2025",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-27-winding-way-water-mill-2025.webp",
    "alt": "27 Winding Way, Water Mill. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "98 Wilkes Lane",
    "area": "Sagaponack",
    "price": "$11,050,000",
    "priceNum": 11050000,
    "date": "2025-01-23",
    "dateText": "Jan 2025",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-98-wilkes-lane-sagaponack-2025.webp",
    "alt": "98 Wilkes Lane, Sagaponack. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "100 Buell Lane",
    "area": "East Hampton",
    "price": "$6,900,000",
    "priceNum": 6900000,
    "date": "2025-01-17",
    "dateText": "Jan 2025",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-100-buell-lane-east-hampton-2025.webp",
    "alt": "100 Buell Lane, East Hampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the buyer"
  },
  {
    "address": "44 Deforest Road",
    "area": "Montauk",
    "price": "$9,000,000",
    "priceNum": 9000000,
    "date": "2024-12-26",
    "dateText": "Dec 2024",
    "hedgerowRole": "Both sides",
    "group": "Oceanfront",
    "barryInvolved": true,
    "image": "/images/hedgerow/sold-44-deforest-road-montauk-2024.webp",
    "alt": "44 Deforest Road, Montauk. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented both sides"
  },
  {
    "address": "11 East Harbor Drive",
    "area": "Sag Harbor",
    "price": "$4,850,000",
    "priceNum": 4850000,
    "date": "2024-12-11",
    "dateText": "Dec 2024",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-11-east-harbor-drive-sag-harbor-2024.webp",
    "alt": "11 East Harbor Drive, Sag Harbor. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the buyer"
  },
  {
    "address": "18 Knoll Road",
    "area": "Southampton",
    "price": "$3,025,000",
    "priceNum": 3025000,
    "date": "2024-11-22",
    "dateText": "Nov 2024",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-18-knoll-road-southampton-2024.webp",
    "alt": "18 Knoll Road, Southampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "1751 Scuttle Hole Road",
    "area": "Bridgehampton",
    "price": "$7,500,000",
    "priceNum": 7500000,
    "date": "2024-11-20",
    "dateText": "Nov 2024",
    "hedgerowRole": "Both sides",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-1751-scuttle-hole-road-bridgehampton-2024.webp",
    "alt": "1751 Scuttle Hole Road, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented both sides"
  },
  {
    "address": "26 S Elroy Drive",
    "area": "Montauk",
    "price": "$9,150,000",
    "priceNum": 9150000,
    "date": "2024-11-12",
    "dateText": "Nov 2024",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-26-s-elroy-drive-montauk-2024.webp",
    "alt": "26 S Elroy Drive, Montauk. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "156 Summerfield Lane",
    "area": "Water Mill",
    "price": "$13,650,000",
    "priceNum": 13650000,
    "date": "2024-11-07",
    "dateText": "Nov 2024",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-156-summerfield-lane-water-mill-2024.webp",
    "alt": "156 Summerfield Lane, Water Mill. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the buyer"
  },
  {
    "address": "1774 Deerfield Road",
    "area": "Water Mill",
    "price": "$2,225,000",
    "priceNum": 2225000,
    "date": "2024-11-01",
    "dateText": "Nov 2024",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-1774-deerfield-road-water-mill-2024.webp",
    "alt": "1774 Deerfield Road, Water Mill. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the buyer"
  },
  {
    "address": "55 Halsey Lane",
    "area": "Bridgehampton",
    "price": "$4,235,000",
    "priceNum": 4235000,
    "date": "2024-10-11",
    "dateText": "Oct 2024",
    "hedgerowRole": "Both sides",
    "group": "Estate and village",
    "barryInvolved": true,
    "image": "/images/hedgerow/sold-55-halsey-lane-bridgehampton-2024.webp",
    "alt": "55 Halsey Lane, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented both sides"
  },
  {
    "address": "454 Hedges Lane",
    "area": "Sagaponack",
    "price": "$6,200,000",
    "priceNum": 6200000,
    "date": "2024-09-19",
    "dateText": "Sep 2024",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "",
    "alt": "",
    "roleLabel": "A Hedgerow transaction"
  },
  {
    "address": "453 Hedges Lane",
    "area": "Sagaponack",
    "price": "$11,000,000",
    "priceNum": 11000000,
    "date": "2024-09-12",
    "dateText": "Sep 2024",
    "hedgerowRole": "Both sides",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-453-hedges-lane-sagaponack-2024.webp",
    "alt": "453 Hedges Lane, Sagaponack. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented both sides"
  },
  {
    "address": "849 Hayground Road",
    "area": "Bridgehampton",
    "price": "$4,250,000",
    "priceNum": 4250000,
    "date": "2024-09-04",
    "dateText": "Sep 2024",
    "hedgerowRole": "Both sides",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-849-hayground-road-bridgehampton-2024.webp",
    "alt": "849 Hayground Road, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented both sides"
  },
  {
    "address": "25 Jobs Lane",
    "area": "Bridgehampton",
    "price": "$6,500,000",
    "priceNum": 6500000,
    "date": "2024-08-22",
    "dateText": "Aug 2024",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-25-jobs-lane-bridgehampton-2024.webp",
    "alt": "25 Jobs Lane, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "81 Ocean Road",
    "area": "Bridgehampton",
    "price": "$6,995,000",
    "priceNum": 6995000,
    "date": "2024-06-28",
    "dateText": "Jun 2024",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-81-ocean-road-bridgehampton-2024.webp",
    "alt": "81 Ocean Road, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "385 Jobs Lane",
    "area": "Bridgehampton",
    "price": "$14,750,000",
    "priceNum": 14750000,
    "date": "2024-06-03",
    "dateText": "Jun 2024",
    "hedgerowRole": "Both sides",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-385-jobs-lane-bridgehampton-2024.webp",
    "alt": "385 Jobs Lane, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented both sides"
  },
  {
    "address": "479 Pauls Lane",
    "area": "Bridgehampton",
    "price": "$4,825,000",
    "priceNum": 4825000,
    "date": "2024-05-30",
    "dateText": "May 2024",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-479-pauls-lane-bridgehampton-2024.webp",
    "alt": "479 Pauls Lane, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "8 John Street",
    "area": "Sag Harbor",
    "price": "$15,518,174",
    "priceNum": 15518174,
    "date": "2024-05-22",
    "dateText": "May 2024",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-8-john-street-sag-harbor-2024.webp",
    "alt": "8 John Street, Sag Harbor. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "332 Parsonage Lane",
    "area": "Sagaponack",
    "price": "$29,500,000",
    "priceNum": 29500000,
    "date": "2024-05-10",
    "dateText": "May 2024",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-332-parsonage-lane-sagaponack-2024.webp",
    "alt": "332 Parsonage Lane, Sagaponack. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "20 Forest Road",
    "area": "Sag Harbor",
    "price": "$10,995,000",
    "priceNum": 10995000,
    "date": "2024-03-13",
    "dateText": "Mar 2024",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-20-forest-road-sag-harbor-2024.webp",
    "alt": "20 Forest Road, Sag Harbor. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "11 Amy’s Lane",
    "area": "East Hampton",
    "price": "$11,200,000",
    "priceNum": 11200000,
    "date": "2024-02-23",
    "dateText": "Feb 2024",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-11-amys-lane-east-hampton-2024.webp",
    "alt": "11 Amy’s Lane, East Hampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "22 Shore Road",
    "area": "Amagansett",
    "price": "$6,425,000",
    "priceNum": 6425000,
    "date": "2024-01-26",
    "dateText": "Jan 2024",
    "hedgerowRole": "Listing",
    "group": "Oceanfront",
    "barryInvolved": true,
    "image": "/images/hedgerow/sold-22-shore-road-amagansett-2024.webp",
    "alt": "22 Shore Road, Amagansett. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "42 Old Montauk Highway",
    "area": "Montauk",
    "price": "$18,500,000",
    "priceNum": 18500000,
    "date": "2023-12-22",
    "dateText": "Dec 2023",
    "hedgerowRole": "Both sides",
    "group": "Oceanfront",
    "barryInvolved": true,
    "image": "/images/hedgerow/sold-42-old-montauk-highway-montauk-2023.webp",
    "alt": "42 Old Montauk Highway, Montauk. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented both sides"
  },
  {
    "address": "156 Summerfield Lane",
    "area": "Water Mill",
    "price": "$12,675,000",
    "priceNum": 12675000,
    "date": "2023-12-20",
    "dateText": "Dec 2023",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-156-summerfield-lane-water-mill-2023.webp",
    "alt": "156 Summerfield Lane, Water Mill. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "72 Birchwood Lane",
    "area": "Bridgehampton",
    "price": "$5,200,000",
    "priceNum": 5200000,
    "date": "2023-11-30",
    "dateText": "Nov 2023",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-72-birchwood-lane-bridgehampton-2023.webp",
    "alt": "72 Birchwood Lane, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "124 Hedges Lane",
    "area": "Sagaponack",
    "price": "$9,500,000",
    "priceNum": 9500000,
    "date": "2023-11-29",
    "dateText": "Nov 2023",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-124-hedges-lane-sagaponack-2023.webp",
    "alt": "124 Hedges Lane, Sagaponack. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "2 Baiting Hollow Road",
    "area": "East Hampton",
    "price": "$3,600,000",
    "priceNum": 3600000,
    "date": "2023-11-22",
    "dateText": "Nov 2023",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-2-baiting-hollow-road-east-hampton-2023.webp",
    "alt": "2 Baiting Hollow Road, East Hampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "48 Forest Road",
    "area": "Sag Harbor",
    "price": "$14,000,000",
    "priceNum": 14000000,
    "date": "2023-10-20",
    "dateText": "Oct 2023",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-48-forest-road-sag-harbor-2023.webp",
    "alt": "48 Forest Road, Sag Harbor. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "191 Highland Terrace",
    "area": "Bridgehampton",
    "price": "$12,200,000",
    "priceNum": 12200000,
    "date": "2023-10-12",
    "dateText": "Oct 2023",
    "hedgerowRole": "Both sides",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-191-highland-terrace-bridgehampton-2023.webp",
    "alt": "191 Highland Terrace, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented both sides"
  },
  {
    "address": "234 Wickapogue Road",
    "area": "Southampton",
    "price": "$12,500,000",
    "priceNum": 12500000,
    "date": "2023-10-10",
    "dateText": "Oct 2023",
    "hedgerowRole": "Both sides",
    "group": "Estate and village",
    "barryInvolved": true,
    "image": "/images/hedgerow/sold-234-wickapogue-road-southampton-2023.webp",
    "alt": "234 Wickapogue Road, Southampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented both sides"
  },
  {
    "address": "30 Lawrence Court",
    "area": "Water Mill",
    "price": "$12,000,000",
    "priceNum": 12000000,
    "date": "2023-10-06",
    "dateText": "Oct 2023",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-30-lawrence-court-water-mill-2023.webp",
    "alt": "30 Lawrence Court, Water Mill. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "219 Sagg Main Street",
    "area": "Sagaponack",
    "price": "$24,500,000",
    "priceNum": 24500000,
    "date": "2023-09-14",
    "dateText": "Sep 2023",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-219-sagg-main-street-sagaponack-2023.webp",
    "alt": "219 Sagg Main Street, Sagaponack. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the buyer"
  },
  {
    "address": "2 Linda Road",
    "area": "Shelter Island",
    "price": "$999,000",
    "priceNum": 999000,
    "date": "2023-08-10",
    "dateText": "Aug 2023",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-2-linda-road-shelter-island-2023.webp",
    "alt": "2 Linda Road, Shelter Island. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the buyer"
  },
  {
    "address": "8 Studio Lane",
    "area": "Southampton",
    "price": "$7,480,000",
    "priceNum": 7480000,
    "date": "2023-06-27",
    "dateText": "Jun 2023",
    "hedgerowRole": "Advised seller",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-8-studio-lane-southampton-2023.webp",
    "alt": "8 Studio Lane, Southampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow advised the seller"
  },
  {
    "address": "9 Bayberry Lane",
    "area": "Sag Harbor",
    "price": "$2,850,000",
    "priceNum": 2850000,
    "date": "2023-06-16",
    "dateText": "Jun 2023",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-9-bayberry-lane-sag-harbor-2023.webp",
    "alt": "9 Bayberry Lane, Sag Harbor. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "193 Sagg Main Street",
    "area": "Sagaponack",
    "price": "$10,500,000",
    "priceNum": 10500000,
    "date": "2023-05-24",
    "dateText": "May 2023",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "barryInvolved": true,
    "image": "/images/hedgerow/sold-193-sagg-main-street-sagaponack-2023.webp",
    "alt": "193 Sagg Main Street, Sagaponack. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the buyer"
  },
  {
    "address": "411 Town Lane",
    "area": "Amagansett",
    "price": "$11,150,000",
    "priceNum": 11150000,
    "date": "2023-04-23",
    "dateText": "Apr 2023",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-411-town-lane-amagansett-2023.webp",
    "alt": "411 Town Lane, Amagansett. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the buyer"
  },
  {
    "address": "46 Spring Street",
    "area": "Sag Harbor",
    "price": "$1,675,000",
    "priceNum": 1675000,
    "date": "2023-04-14",
    "dateText": "Apr 2023",
    "hedgerowRole": "Both sides",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-46-spring-street-sag-harbor-2023.webp",
    "alt": "46 Spring Street, Sag Harbor. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented both sides"
  },
  {
    "address": "5 Knoll Lane",
    "area": "Wainscott",
    "price": "$2,125,000",
    "priceNum": 2125000,
    "date": "2023-03-31",
    "dateText": "Mar 2023",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-5-knoll-lane-wainscott-2023.webp",
    "alt": "5 Knoll Lane, Wainscott. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "151 Cedar Street",
    "area": "East Hampton",
    "price": "$4,600,000",
    "priceNum": 4600000,
    "date": "2023-03-16",
    "dateText": "Mar 2023",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-151-cedar-street-east-hampton-2023.webp",
    "alt": "151 Cedar Street, East Hampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "51 Wainscott Hollow Road",
    "area": "Wainscott",
    "price": "$7,100,000",
    "priceNum": 7100000,
    "date": "2023-02-07",
    "dateText": "Feb 2023",
    "hedgerowRole": "Both sides",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-51-wainscott-hollow-road-wainscott-2023.webp",
    "alt": "51 Wainscott Hollow Road, Wainscott. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented both sides"
  },
  {
    "address": "180 Rose Hill Road",
    "area": "Water Mill",
    "price": "$20,000,000",
    "priceNum": 20000000,
    "date": "2023-01-13",
    "dateText": "Jan 2023",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-180-rose-hill-road-water-mill-2023.webp",
    "alt": "180 Rose Hill Road, Water Mill. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "31 Morrison Lane",
    "area": "Water Mill",
    "price": "$15,250,000",
    "priceNum": 15250000,
    "date": "2023-01-06",
    "dateText": "Jan 2023",
    "hedgerowRole": "Buyer side",
    "group": "Waterfront",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-31-morrison-lane-water-mill-2023.webp",
    "alt": "31 Morrison Lane, Water Mill. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the buyer"
  },
  {
    "address": "690 Ocean Road",
    "area": "Bridgehampton",
    "price": "$6,250,000",
    "priceNum": 6250000,
    "date": "2023-01-06",
    "dateText": "Jan 2023",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-690-ocean-road-bridgehampton-2023.webp",
    "alt": "690 Ocean Road, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "57 Wainscott Hollow Road",
    "area": "Wainscott",
    "price": "$9,100,000",
    "priceNum": 9100000,
    "date": "2022-11-21",
    "dateText": "Nov 2022",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-57-wainscott-hollow-road-wainscott-2022.webp",
    "alt": "57 Wainscott Hollow Road, Wainscott. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "5 Gardiners Bay Drive",
    "area": "Shelter Island",
    "price": "$1,751,000",
    "priceNum": 1751000,
    "date": "2022-10-24",
    "dateText": "Oct 2022",
    "hedgerowRole": "Both sides",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-5-gardiners-bay-drive-shelter-island-2022.webp",
    "alt": "5 Gardiners Bay Drive, Shelter Island. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented both sides"
  },
  {
    "address": "42 Old Montauk Highway",
    "area": "Montauk",
    "price": "$25,000,000",
    "priceNum": 25000000,
    "date": "2022-10-21",
    "dateText": "Oct 2022",
    "hedgerowRole": "Both sides",
    "group": "Oceanfront",
    "barryInvolved": true,
    "image": "/images/hedgerow/sold-42-old-montauk-highway-montauk-2022.webp",
    "alt": "42 Old Montauk Highway, Montauk. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented both sides"
  },
  {
    "address": "4 Bay Lane",
    "area": "Water Mill",
    "price": "$12,500,000",
    "priceNum": 12500000,
    "date": "2022-10-03",
    "dateText": "Oct 2022",
    "hedgerowRole": "Buyer side",
    "group": "Waterfront",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-4-bay-lane-water-mill-2022.webp",
    "alt": "4 Bay Lane, Water Mill. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the buyer"
  },
  {
    "address": "63 Duck Pond Lane",
    "area": "Southampton",
    "price": "$30,000,000",
    "priceNum": 30000000,
    "date": "2022-08-05",
    "dateText": "Aug 2022",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-63-duck-pond-lane-southampton-2022.webp",
    "alt": "63 Duck Pond Lane, Southampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "1080 & 1100 Meadow Lane",
    "area": "Southampton",
    "price": "$66,250,000",
    "priceNum": 66250000,
    "date": "2022-07-25",
    "dateText": "Jul 2022",
    "hedgerowRole": "Both sides",
    "group": "Oceanfront",
    "barryInvolved": true,
    "image": "/images/hedgerow/sold-1080-1100-meadow-lane-southampton-2022.webp",
    "alt": "1080 & 1100 Meadow Lane, Southampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented both sides"
  },
  {
    "address": "68 Dune Road",
    "area": "Bridgehampton",
    "price": "$8,100,000",
    "priceNum": 8100000,
    "date": "2022-07-20",
    "dateText": "Jul 2022",
    "hedgerowRole": "Both sides",
    "group": "Waterfront",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-68-dune-road-bridgehampton-2022.webp",
    "alt": "68 Dune Road, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented both sides"
  },
  {
    "address": "11 Grand Street",
    "area": "Sag Harbor",
    "price": "$1,600,000",
    "priceNum": 1600000,
    "date": "2022-07-18",
    "dateText": "Jul 2022",
    "hedgerowRole": "Both sides",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-11-grand-street-sag-harbor-2022.webp",
    "alt": "11 Grand Street, Sag Harbor. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented both sides"
  },
  {
    "address": "35 Potato Road & 543 Daniels Lane",
    "area": "Sagaponack",
    "price": "$46,500,000",
    "priceNum": 46500000,
    "date": "2022-05-16",
    "dateText": "May 2022",
    "hedgerowRole": "Buyer side",
    "group": "Oceanfront",
    "barryInvolved": true,
    "image": "/images/hedgerow/sold-35-potato-road-543-daniels-lane-sagaponack-2022.webp",
    "alt": "35 Potato Road & 543 Daniels Lane, Sagaponack. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the buyer"
  },
  {
    "address": "55 Marine Boulevard",
    "area": "Amagansett",
    "price": "$9,000,000",
    "priceNum": 9000000,
    "date": "2022-05-01",
    "dateText": "May 2022",
    "hedgerowRole": "Both sides",
    "group": "Oceanfront",
    "barryInvolved": true,
    "image": "/images/hedgerow/sold-55-marine-boulevard-amagansett-2022.webp",
    "alt": "55 Marine Boulevard, Amagansett. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented both sides"
  },
  {
    "address": "34 Cobb Hill Lane",
    "area": "Water Mill",
    "price": "$11,500,000",
    "priceNum": 11500000,
    "date": "2022-03-08",
    "dateText": "Mar 2022",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-34-cobb-hill-lane-water-mill-2022.webp",
    "alt": "34 Cobb Hill Lane, Water Mill. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the buyer"
  },
  {
    "address": "190 Bridies Path",
    "area": "Southampton",
    "price": "$2,350,000",
    "priceNum": 2350000,
    "date": "2022-03-07",
    "dateText": "Mar 2022",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-190-bridies-path-southampton-2022.webp",
    "alt": "190 Bridies Path, Southampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the buyer"
  },
  {
    "address": "22 Bay View Court",
    "area": "Sag Harbor",
    "price": "$17,000,000",
    "priceNum": 17000000,
    "date": "2022-03-04",
    "dateText": "Mar 2022",
    "hedgerowRole": "Listing",
    "group": "Waterfront",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-22-bay-view-court-sag-harbor-2022.webp",
    "alt": "22 Bay View Court, Sag Harbor. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "431 Old Sag Harbor Road",
    "area": "Bridgehampton",
    "price": "$7,200,000",
    "priceNum": 7200000,
    "date": "2022-03-04",
    "dateText": "Mar 2022",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-431-old-sag-harbor-road-bridgehampton-2022.webp",
    "alt": "431 Old Sag Harbor Road, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "6 Woodhollow Drive",
    "area": "East Hampton",
    "price": "$2,350,000",
    "priceNum": 2350000,
    "date": "2022-02-04",
    "dateText": "Feb 2022",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-6-woodhollow-drive-east-hampton-2022.webp",
    "alt": "6 Woodhollow Drive, East Hampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "59 Springwood Lane",
    "area": "East Hampton",
    "price": "$1,945,000",
    "priceNum": 1945000,
    "date": "2022-01-28",
    "dateText": "Jan 2022",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-59-springwood-lane-east-hampton-2022.webp",
    "alt": "59 Springwood Lane, East Hampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the buyer"
  },
  {
    "address": "6 Polo Court",
    "area": "Bridgehampton",
    "price": "$12,400,000",
    "priceNum": 12400000,
    "date": "2022-01-02",
    "dateText": "Jan 2022",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-6-polo-court-bridgehampton-2022.webp",
    "alt": "6 Polo Court, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "40 Hedges Banks Drive",
    "area": "East Hampton",
    "price": "$5,500,000",
    "priceNum": 5500000,
    "date": "2022",
    "dateText": "2022",
    "hedgerowRole": "Listing",
    "group": "Waterfront",
    "barryInvolved": true,
    "image": "/images/hedgerow/sold-40-hedges-banks-drive-east-hampton-2022.webp",
    "alt": "40 Hedges Banks Drive, East Hampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "442 Further Lane",
    "area": "East Hampton",
    "price": "$55,000,000",
    "priceNum": 55000000,
    "date": "2021-12-06",
    "dateText": "Dec 2021",
    "hedgerowRole": "Listing",
    "group": "Oceanfront",
    "barryInvolved": true,
    "image": "/images/hedgerow/sold-442-further-lane-east-hampton-2021.webp",
    "alt": "442 Further Lane, East Hampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "24 Two Mile Hollow Road",
    "area": "East Hampton",
    "price": "$19,500,000",
    "priceNum": 19500000,
    "date": "2021-11-10",
    "dateText": "Nov 2021",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-24-two-mile-hollow-road-east-hampton-2021.webp",
    "alt": "24 Two Mile Hollow Road, East Hampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "93 Middle Lane",
    "area": "East Hampton",
    "price": "$13,100,000",
    "priceNum": 13100000,
    "date": "2021-09-17",
    "dateText": "Sep 2021",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-93-middle-lane-east-hampton-2021.webp",
    "alt": "93 Middle Lane, East Hampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the buyer"
  },
  {
    "address": "90 Jule Pond Drive",
    "area": "Water Mill",
    "price": "$105,000,000",
    "priceNum": 105000000,
    "date": "2021-08-17",
    "dateText": "Aug 2021",
    "hedgerowRole": "Advised seller",
    "group": "Oceanfront",
    "barryInvolved": true,
    "image": "/images/hedgerow/sold-90-jule-pond-drive-water-mill-2021.webp",
    "alt": "90 Jule Pond Drive, Water Mill. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow advised the seller"
  },
  {
    "address": "26 On the Bluff",
    "area": "Sag Harbor",
    "price": "$11,995,000",
    "priceNum": 11995000,
    "date": "2021-07-26",
    "dateText": "Jul 2021",
    "hedgerowRole": "Listing",
    "group": "Waterfront",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-26-on-the-bluff-sag-harbor-2021.webp",
    "alt": "26 On the Bluff, Sag Harbor. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "28 Hedges Lane",
    "area": "Amagansett",
    "price": "$4,250,000",
    "priceNum": 4250000,
    "date": "2021-05-26",
    "dateText": "May 2021",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-28-hedges-lane-amagansett-2021.webp",
    "alt": "28 Hedges Lane, Amagansett. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "194 Middle Line Highway",
    "area": "Southampton",
    "price": "$3,768,750",
    "priceNum": 3768750,
    "date": "2021-05-15",
    "dateText": "May 2021",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-194-middle-line-highway-southampton-2021.webp",
    "alt": "194 Middle Line Highway, Southampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "67 Surfside Drive",
    "area": "Bridgehampton",
    "price": "$28,500,000",
    "priceNum": 28500000,
    "date": "2021-05-13",
    "dateText": "May 2021",
    "hedgerowRole": "Buyer side",
    "group": "Oceanfront",
    "barryInvolved": true,
    "image": "/images/hedgerow/sold-67-surfside-drive-bridgehampton-2021.webp",
    "alt": "67 Surfside Drive, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the buyer"
  },
  {
    "address": "49 Birchwood Lane",
    "area": "Bridgehampton",
    "price": "$1,400,000",
    "priceNum": 1400000,
    "date": "2021-04-08",
    "dateText": "Apr 2021",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-49-birchwood-lane-bridgehampton-2021.webp",
    "alt": "49 Birchwood Lane, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the buyer"
  },
  {
    "address": "40 Meadow Lane",
    "area": "Southampton",
    "price": "$42,920,000",
    "priceNum": 42920000,
    "date": "2021-04",
    "dateText": "Apr 2021",
    "hedgerowRole": "Both sides",
    "group": "Oceanfront",
    "barryInvolved": true,
    "image": "/images/hedgerow/sold-40-meadow-lane-southampton-2021.webp",
    "alt": "40 Meadow Lane, Southampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "A Hedgerow transaction"
  },
  {
    "address": "675 Flying Point Road",
    "area": "Water Mill",
    "price": "$17,500,000",
    "priceNum": 17500000,
    "date": "2021-03-24",
    "dateText": "Mar 2021",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-675-flying-point-road-water-mill-2021.webp",
    "alt": "675 Flying Point Road, Water Mill. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "5 Wagon Lane",
    "area": "East Hampton",
    "price": "$3,250,000",
    "priceNum": 3250000,
    "date": "2021-02-21",
    "dateText": "Feb 2021",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-5-wagon-lane-east-hampton-2021.webp",
    "alt": "5 Wagon Lane, East Hampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the buyer"
  },
  {
    "address": "9 Morgan Hill Lane",
    "area": "Bridgehampton",
    "price": "$18,000,000",
    "priceNum": 18000000,
    "date": "2021-01-21",
    "dateText": "Jan 2021",
    "hedgerowRole": "Listing",
    "group": "Waterfront",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-9-morgan-hill-lane-bridgehampton-2021.webp",
    "alt": "9 Morgan Hill Lane, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "222 Two Holes of Water Road",
    "area": "East Hampton",
    "price": "$2,150,000",
    "priceNum": 2150000,
    "date": "2021-01-21",
    "dateText": "Jan 2021",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-222-two-holes-of-water-road-east-hampton-2021.webp",
    "alt": "222 Two Holes of Water Road, East Hampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the buyer"
  },
  {
    "address": "14 Maidstone Avenue",
    "area": "East Hampton",
    "price": "$1,850,000",
    "priceNum": 1850000,
    "date": "2021-01-11",
    "dateText": "Jan 2021",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-14-maidstone-avenue-east-hampton-2021.webp",
    "alt": "14 Maidstone Avenue, East Hampton. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow represented the seller"
  },
  {
    "address": "432 Park Avenue, PH 82",
    "area": "New York, NY",
    "price": "$70,500,000",
    "priceNum": 70500000,
    "date": "2021",
    "dateText": "2021",
    "hedgerowRole": "Advised seller",
    "group": "Estate and village",
    "barryInvolved": false,
    "image": "/images/hedgerow/sold-432-park-avenue-ph-82-new-york-ny-2021.webp",
    "alt": "432 Park Avenue, PH 82, New York, NY. Photo courtesy of Hedgerow Exclusive Properties",
    "roleLabel": "Hedgerow advised the seller"
  }
];

/** Hedgerow firm history: prominent deals before 2021 or without a published date. Not Barry's personal transactions. */
export const hedgerowFirmHistory: HedgerowSoldDeal[] = [
  {
    "address": "70 & 71 Cobb Lane",
    "area": "Water Mill",
    "price": "$121,500,000",
    "priceNum": 121500000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Both sides",
    "group": "Waterfront",
    "roleLabel": "Hedgerow represented both sides",
    "image": "/images/hedgerow/firm-70-71-cobb-lane-water-mill.webp",
    "alt": "70 & 71 Cobb Lane, Water Mill. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "93, 97, 101 Lily Pond Lane",
    "area": "East Hampton",
    "price": "$110,000,000",
    "priceNum": 110000000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Listing",
    "group": "Oceanfront",
    "roleLabel": "Hedgerow represented the seller",
    "image": "/images/hedgerow/firm-93-97-101-lily-pond-lane-east-hampton.webp",
    "alt": "93, 97, 101 Lily Pond Lane, East Hampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "278 Further Lane",
    "area": "East Hampton",
    "price": "$103,000,000",
    "priceNum": 103000000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Both sides",
    "group": "Oceanfront",
    "roleLabel": "Hedgerow represented both sides",
    "image": "/images/hedgerow/firm-278-further-lane-east-hampton.webp",
    "alt": "278 Further Lane, East Hampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "Lily Pond Compound",
    "area": "East Hampton",
    "price": "$93,000,000",
    "priceNum": 93000000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Buyer side",
    "group": "Oceanfront",
    "roleLabel": "Hedgerow represented the buyer",
    "image": "/images/hedgerow/firm-lily-pond-compound-east-hampton.webp",
    "alt": "Lily Pond Compound, East Hampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "70 Further Lane",
    "area": "East Hampton",
    "price": "$60,000,000",
    "priceNum": 60000000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Buyer side",
    "group": "Oceanfront",
    "roleLabel": "Hedgerow represented the buyer",
    "image": "/images/hedgerow/firm-70-further-lane-east-hampton.webp",
    "alt": "70 Further Lane, East Hampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "616 & 640 Ox Pasture",
    "area": "Southampton",
    "price": "$53,500,000",
    "priceNum": 53500000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Buyer side",
    "group": "Waterfront",
    "roleLabel": "Hedgerow represented the buyer",
    "image": "/images/hedgerow/firm-616-640-ox-pasture-southampton.webp",
    "alt": "616 & 640 Ox Pasture, Southampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "296 & 311 Surfside Drive",
    "area": "Bridgehampton",
    "price": "$52,150,000",
    "priceNum": 52150000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Both sides",
    "group": "Oceanfront",
    "roleLabel": "Hedgerow represented both sides",
    "image": "/images/hedgerow/firm-296-311-surfside-drive-bridgehampton.webp",
    "alt": "296 & 311 Surfside Drive, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "442 Further Lane",
    "area": "East Hampton",
    "price": "$51,000,000",
    "priceNum": 51000000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Advised both sides",
    "group": "Oceanfront",
    "roleLabel": "Hedgerow advised both sides",
    "image": "/images/hedgerow/firm-442-further-lane-east-hampton.webp",
    "alt": "442 Further Lane, East Hampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "187 Dune Road",
    "area": "Bridgehampton",
    "price": "$50,150,000",
    "priceNum": 50150000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Both sides",
    "group": "Oceanfront",
    "roleLabel": "Hedgerow represented both sides",
    "image": "/images/hedgerow/firm-187-dune-road-bridgehampton.webp",
    "alt": "187 Dune Road, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "16 Cliff Drive & 8 Old Montauk Highway",
    "area": "Montauk",
    "price": "$50,000,000",
    "priceNum": 50000000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Listing",
    "group": "Oceanfront",
    "roleLabel": "Hedgerow represented the seller",
    "image": "/images/hedgerow/firm-16-cliff-drive-8-old-montauk-highway-montauk.webp",
    "alt": "16 Cliff Drive & 8 Old Montauk Highway, Montauk. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "194 & 218 Meadowlark Lane",
    "area": "Bridgehampton",
    "price": "$45,000,000",
    "priceNum": 45000000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Both sides",
    "group": "Waterfront",
    "roleLabel": "Hedgerow represented both sides",
    "image": "/images/hedgerow/firm-194-218-meadowlark-lane-bridgehampton.webp",
    "alt": "194 & 218 Meadowlark Lane, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "1400 Meadow Lane",
    "area": "Southampton",
    "price": "$39,500,000",
    "priceNum": 39500000,
    "date": "2020-12-10",
    "dateText": "Dec 2020",
    "hedgerowRole": "Buyer side",
    "group": "Oceanfront",
    "roleLabel": "Hedgerow represented the buyer",
    "image": "/images/hedgerow/firm-1400-meadow-lane-southampton.webp",
    "alt": "1400 Meadow Lane, Southampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "263 Surfside Drive",
    "area": "Bridgehampton",
    "price": "$39,250,000",
    "priceNum": 39250000,
    "date": "2019-06-20",
    "dateText": "Jun 2019",
    "hedgerowRole": "Listing",
    "group": "Oceanfront",
    "roleLabel": "Hedgerow represented the seller",
    "image": "/images/hedgerow/firm-263-surfside-drive-bridgehampton.webp",
    "alt": "263 Surfside Drive, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "260 & 264 Jobs Lane",
    "area": "Bridgehampton",
    "price": "$38,000,000",
    "priceNum": 38000000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Both sides",
    "group": "Waterfront",
    "roleLabel": "Hedgerow represented both sides",
    "image": "/images/hedgerow/firm-260-264-jobs-lane-bridgehampton.webp",
    "alt": "260 & 264 Jobs Lane, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "784 Meadow Lane",
    "area": "Southampton",
    "price": "$37,500,000",
    "priceNum": 37500000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Both sides",
    "group": "Oceanfront",
    "roleLabel": "Hedgerow represented both sides",
    "image": "/images/hedgerow/firm-784-meadow-lane-southampton.webp",
    "alt": "784 Meadow Lane, Southampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "121 Further Lane & 40 Middle Lane",
    "area": "East Hampton",
    "price": "$35,250,000",
    "priceNum": 35250000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "roleLabel": "Hedgerow represented the buyer",
    "image": "/images/hedgerow/firm-121-further-lane-40-middle-lane-east-hampton.webp",
    "alt": "121 Further Lane & 40 Middle Lane, East Hampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "55 Coopers Neck Lane",
    "area": "Southampton",
    "price": "$34,000,000",
    "priceNum": 34000000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "roleLabel": "Hedgerow represented the seller",
    "image": "/images/hedgerow/firm-55-coopers-neck-lane-southampton.webp",
    "alt": "55 Coopers Neck Lane, Southampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "35 Dune Road",
    "area": "Bridgehampton",
    "price": "$33,500,000",
    "priceNum": 33500000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Both sides",
    "group": "Oceanfront",
    "roleLabel": "Hedgerow represented both sides",
    "image": "/images/hedgerow/firm-35-dune-road-bridgehampton.webp",
    "alt": "35 Dune Road, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "390 Fowler Street",
    "area": "Southampton",
    "price": "$32,500,000",
    "priceNum": 32500000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Both sides",
    "group": "Oceanfront",
    "roleLabel": "Hedgerow represented both sides",
    "image": "/images/hedgerow/firm-390-fowler-street-southampton.webp",
    "alt": "390 Fowler Street, Southampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "29 Spaeth Lane",
    "area": "East Hampton",
    "price": "$32,500,000",
    "priceNum": 32500000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Both sides",
    "group": "Oceanfront",
    "roleLabel": "Hedgerow represented both sides",
    "image": "/images/hedgerow/firm-29-spaeth-lane-east-hampton.webp",
    "alt": "29 Spaeth Lane, East Hampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "325 Bluff Road",
    "area": "Amagansett",
    "price": "$32,000,000",
    "priceNum": 32000000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Both sides",
    "group": "Oceanfront",
    "roleLabel": "Hedgerow represented both sides",
    "image": "/images/hedgerow/firm-325-bluff-road-amagansett.webp",
    "alt": "325 Bluff Road, Amagansett. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "950 Meadow Lane",
    "area": "Southampton",
    "price": "$29,500,000",
    "priceNum": 29500000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Buyer side",
    "group": "Oceanfront",
    "roleLabel": "Hedgerow represented the buyer",
    "image": "/images/hedgerow/firm-950-meadow-lane-southampton.webp",
    "alt": "950 Meadow Lane, Southampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "900 Meadow Lane",
    "area": "Southampton",
    "price": "$28,000,000",
    "priceNum": 28000000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Both sides",
    "group": "Oceanfront",
    "roleLabel": "Hedgerow represented both sides",
    "image": "/images/hedgerow/firm-900-meadow-lane-southampton.webp",
    "alt": "900 Meadow Lane, Southampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "159 Trees Lane",
    "area": "Sagaponack",
    "price": "$26,000,000",
    "priceNum": 26000000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Listing",
    "group": "Oceanfront",
    "roleLabel": "Hedgerow represented the seller",
    "image": "/images/hedgerow/firm-159-trees-lane-sagaponack.webp",
    "alt": "159 Trees Lane, Sagaponack. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "49 Wainscott Hollow Road",
    "area": "Wainscott",
    "price": "$21,000,000",
    "priceNum": 21000000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "roleLabel": "Hedgerow represented the seller",
    "image": "/images/hedgerow/firm-49-wainscott-hollow-road-wainscott.webp",
    "alt": "49 Wainscott Hollow Road, Wainscott. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "266 & 300 Sagaponack Road",
    "area": "Sagaponack",
    "price": "$18,500,000",
    "priceNum": 18500000,
    "date": "2020-02-07",
    "dateText": "Feb 2020",
    "hedgerowRole": "Listing",
    "group": "Waterfront",
    "roleLabel": "Hedgerow represented the seller",
    "image": "/images/hedgerow/firm-266-300-sagaponack-road-sagaponack.webp",
    "alt": "266 & 300 Sagaponack Road, Sagaponack. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "70 Matthews Lane",
    "area": "Bridgehampton",
    "price": "$17,250,000",
    "priceNum": 17250000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "roleLabel": "Hedgerow represented the seller",
    "image": "/images/hedgerow/firm-70-matthews-lane-bridgehampton.webp",
    "alt": "70 Matthews Lane, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "Casa Amor",
    "area": "Montauk",
    "price": "$17,000,000",
    "priceNum": 17000000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Listing",
    "group": "Oceanfront",
    "roleLabel": "Hedgerow represented the seller",
    "image": "/images/hedgerow/firm-casa-amor-montauk.webp",
    "alt": "Casa Amor, Montauk. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "115 Hand Lane",
    "area": "Amagansett",
    "price": "$14,950,000",
    "priceNum": 14950000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Both sides",
    "group": "Estate and village",
    "roleLabel": "Hedgerow represented both sides",
    "image": "/images/hedgerow/firm-115-hand-lane-amagansett.webp",
    "alt": "115 Hand Lane, Amagansett. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "219 Sagg Main Street",
    "area": "Sagaponack",
    "price": "$12,050,000",
    "priceNum": 12050000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "roleLabel": "Hedgerow represented the buyer",
    "image": "/images/hedgerow/firm-219-sagg-main-street-sagaponack.webp",
    "alt": "219 Sagg Main Street, Sagaponack. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "5 Agnew Avenue",
    "area": "Montauk",
    "price": "$10,500,000",
    "priceNum": 10500000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Advised buyer",
    "group": "Estate and village",
    "roleLabel": "Hedgerow advised the buyer",
    "image": "/images/hedgerow/firm-5-agnew-avenue-montauk.webp",
    "alt": "5 Agnew Avenue, Montauk. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "1076 Ocean Road",
    "area": "Bridgehampton",
    "price": "$10,300,000",
    "priceNum": 10300000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Listing",
    "group": "Waterfront",
    "roleLabel": "Hedgerow represented the seller",
    "image": "/images/hedgerow/firm-1076-ocean-road-bridgehampton.webp",
    "alt": "1076 Ocean Road, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "81 Jennifir Lane",
    "area": "Bridgehampton",
    "price": "$7,300,000",
    "priceNum": 7300000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Both sides",
    "group": "Waterfront",
    "roleLabel": "Hedgerow represented both sides",
    "image": "/images/hedgerow/firm-81-jennifir-lane-bridgehampton.webp",
    "alt": "81 Jennifir Lane, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "161 Summerfield Lane (As is)",
    "area": "Water Mill",
    "price": "$7,300,000",
    "priceNum": 7300000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "roleLabel": "Hedgerow represented the seller",
    "image": "/images/hedgerow/firm-161-summerfield-lane-as-is-water-mill.webp",
    "alt": "161 Summerfield Lane (As is), Water Mill. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "24 Forest Road",
    "area": "Sag Harbor",
    "price": "$7,250,000",
    "priceNum": 7250000,
    "date": "2020-07-13",
    "dateText": "Jul 2020",
    "hedgerowRole": "Listing",
    "group": "Waterfront",
    "roleLabel": "Hedgerow represented the seller",
    "image": "/images/hedgerow/firm-24-forest-road-sag-harbor.webp",
    "alt": "24 Forest Road, Sag Harbor. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "99 S Main Street",
    "area": "Southampton",
    "price": "$6,500,000",
    "priceNum": 6500000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Listing",
    "group": "Waterfront",
    "roleLabel": "Hedgerow represented the seller",
    "image": "/images/hedgerow/firm-99-s-main-street-southampton.webp",
    "alt": "99 S Main Street, Southampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "490 Hayground Road",
    "area": "Bridgehampton",
    "price": "$4,100,000",
    "priceNum": 4100000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "roleLabel": "Hedgerow represented the buyer",
    "image": "/images/hedgerow/firm-490-hayground-road-bridgehampton.webp",
    "alt": "490 Hayground Road, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "17 Water Mill Heights",
    "area": "Water Mill",
    "price": "$3,850,000",
    "priceNum": 3850000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "roleLabel": "Hedgerow represented the buyer",
    "image": "/images/hedgerow/firm-17-water-mill-heights-water-mill.webp",
    "alt": "17 Water Mill Heights, Water Mill. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "724 Butter Lane",
    "area": "Bridgehampton",
    "price": "$3,100,000",
    "priceNum": 3100000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "roleLabel": "Hedgerow represented the buyer",
    "image": "/images/hedgerow/firm-724-butter-lane-bridgehampton.webp",
    "alt": "724 Butter Lane, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "9 Seasons Lane",
    "area": "Southampton",
    "price": "$2,800,000",
    "priceNum": 2800000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "roleLabel": "Hedgerow represented the seller",
    "image": "/images/hedgerow/firm-9-seasons-lane-southampton.webp",
    "alt": "9 Seasons Lane, Southampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "44 Robeson Boulevard",
    "area": "Sag Harbor",
    "price": "$2,800,000",
    "priceNum": 2800000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "roleLabel": "Hedgerow represented the seller",
    "image": "/images/hedgerow/firm-44-robeson-boulevard-sag-harbor.webp",
    "alt": "44 Robeson Boulevard, Sag Harbor. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "82 Whooping Hollow Road",
    "area": "East Hampton",
    "price": "$2,750,000",
    "priceNum": 2750000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "roleLabel": "Hedgerow represented the buyer",
    "image": "/images/hedgerow/firm-82-whooping-hollow-road-east-hampton.webp",
    "alt": "82 Whooping Hollow Road, East Hampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "10 Dominy Court",
    "area": "East Hampton",
    "price": "$2,595,000",
    "priceNum": 2595000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "roleLabel": "Hedgerow represented the seller",
    "image": "/images/hedgerow/firm-10-dominy-court-east-hampton.webp",
    "alt": "10 Dominy Court, East Hampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "6 Holly Place",
    "area": "East Hampton",
    "price": "$2,300,000",
    "priceNum": 2300000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "roleLabel": "Hedgerow represented the buyer",
    "image": "/images/hedgerow/firm-6-holly-place-east-hampton.webp",
    "alt": "6 Holly Place, East Hampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "10 Hedges Avenue",
    "area": "East Hampton",
    "price": "$2,200,000",
    "priceNum": 2200000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Listing",
    "group": "Estate and village",
    "roleLabel": "Hedgerow represented the seller",
    "image": "/images/hedgerow/firm-10-hedges-avenue-east-hampton.webp",
    "alt": "10 Hedges Avenue, East Hampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "14 Katie Lane",
    "area": "Amagansett",
    "price": "$1,825,000",
    "priceNum": 1825000,
    "date": "2020-08-11",
    "dateText": "Aug 2020",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "roleLabel": "Hedgerow represented the buyer",
    "image": "/images/hedgerow/firm-14-katie-lane-amagansett.webp",
    "alt": "14 Katie Lane, Amagansett. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "32A Vail Avenue",
    "area": "East Quogue",
    "price": "$1,650,000",
    "priceNum": 1650000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "roleLabel": "Hedgerow represented the buyer",
    "image": "/images/hedgerow/firm-32a-vail-avenue-east-quogue.webp",
    "alt": "32A Vail Avenue, East Quogue. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "828 Old Sag Harbor Road",
    "area": "Bridgehampton",
    "price": "$1,550,000",
    "priceNum": 1550000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Both sides",
    "group": "Estate and village",
    "roleLabel": "Hedgerow represented both sides",
    "image": "/images/hedgerow/firm-828-old-sag-harbor-road-bridgehampton.webp",
    "alt": "828 Old Sag Harbor Road, Bridgehampton. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "64 Hillside Avenue",
    "area": "Sag Harbor",
    "price": "$1,200,000",
    "priceNum": 1200000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "roleLabel": "Hedgerow represented the buyer",
    "image": "/images/hedgerow/firm-64-hillside-avenue-sag-harbor.webp",
    "alt": "64 Hillside Avenue, Sag Harbor. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "25 Ridge Drive",
    "area": "Wainscott",
    "price": "$1,050,000",
    "priceNum": 1050000,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "roleLabel": "Hedgerow represented the buyer",
    "image": "/images/hedgerow/firm-25-ridge-drive-wainscott.webp",
    "alt": "25 Ridge Drive, Wainscott. Photo courtesy of Hedgerow Exclusive Properties"
  },
  {
    "address": "2004 Montauk Highway, #822",
    "area": "Amagansett",
    "price": "$412,500",
    "priceNum": 412500,
    "date": "",
    "dateText": "",
    "hedgerowRole": "Buyer side",
    "group": "Estate and village",
    "roleLabel": "Hedgerow represented the buyer",
    "image": "/images/hedgerow/firm-2004-montauk-highway-822-amagansett.webp",
    "alt": "2004 Montauk Highway, #822, Amagansett. Photo courtesy of Hedgerow Exclusive Properties"
  }
];
