// Generated from hedgerowexclusive.com/press (Hedgerow Exclusive Properties press page), October 2026.
// Headlines, outlets, and dates follow Hedgerow's press page; links go to the original publisher.
// Summaries are original one-line descriptions. Do not paste article text.
// Featured items are independent articles that name Barry; each URL was fetched and the mention confirmed (Oct 2026).
import { PRESS_QUARTER_CARD } from "@/lib/seo-copy";

export interface PressItem {
  outlet: string;
  title: string;
  /** ISO date, YYYY-MM-DD or YYYY-MM when Hedgerow publishes month only */
  date: string;
  dateText: string;
  summary: string;
  /** Original publisher URL */
  url: string;
  image?: string;
  alt?: string;
  /** How Barry appears in the piece (featured items only). */
  role?: string;
}

/** Barry's own mentions, shown first as Featured. */
export const featuredPress: PressItem[] = [
  {
    outlet: "Behind The Hedges",
    title: "Spring Awakens East End Real Estate, But Who Has the Upper Hand?",
    date: "2026-04-07",
    dateText: "April 7, 2026",
    role: "Quoted",
    summary: "East End agents on the early spring market. Barry is quoted, with a Hedgerow listing in Shelter Island Heights pictured.",
    url: "https://behindthehedges.com/spring-awakens-east-end-real-estate-upper-hand/",
  },
  {
    outlet: PRESS_QUARTER_CARD.outlet,
    title: PRESS_QUARTER_CARD.title,
    date: "2025-08-14",
    dateText: "August 14, 2025",
    role: "Roundtable",
    summary: PRESS_QUARTER_CARD.dek,
    url: PRESS_QUARTER_CARD.url,
  },
  {
    outlet: "Behind The Hedges",
    title: "Checking in on the Hamptons Real Estate Market",
    date: "2025-05-24",
    dateText: "May 24, 2025",
    role: "Quoted",
    summary: "A pre-summer read on inventory and velocity across the East End, with Barry among the agents quoted.",
    url: "https://behindthehedges.com/checking-in-on-the-hamptons-real-estate-market/",
  },
  {
    outlet: "27East",
    title: "Taking the Pulse of the Hamptons Real Estate Market",
    date: "2025-02-19",
    dateText: "February 19, 2025",
    role: "Panelist",
    summary: "A 27East panel on the state of the Hamptons market, with Barry among the speakers.",
    url: "https://www.27east.com/real-estate-news/taking-the-pulse-of-the-market-2341562/",
  },
  {
    outlet: "Hamptons Real Estate Showcase",
    title: "Realty Check",
    date: "2024-07-30",
    dateText: "July 30, 2024",
    role: "Quoted",
    summary: "A historic Shelter Island Heights waterfront home offered through Hedgerow, with Barry on how rarely Heights waterfront comes to market.",
    url: "https://hamptonsrealestateshowcase.com/latest-news/realty-check-51/",
  },
    {"outlet": "James Lane Post", "title": "Inside The Vision: A Deep Dive With Hedgerow Exclusive Founders Gary Cooper & Preston Kaye, And Their Team", "date": "2024-07-29", "dateText": "July 29, 2024", "summary": "An interview with Hedgerow founders Gary Cooper and Preston Kaye and members of the team, with Barry among those interviewed.", "role": "Interviewed", "url": "https://jameslanepost.com/inside-the-vision-a-deep-dive-with-hedgerow-exclusive-founders-gary-cooper-preston-kaye-and-their-elite-team/07/29/2024/Hamptons-News-Happenings", "image": "/images/press/hedgerow/inside-the-vision-a-deep-dive-with-hedgerow-exclusive-founde.webp", "alt": "Inside The Vision: A Deep Dive With Hedgerow Exclusive Founders Gary Cooper & Preston Kaye, And Their Team, James Lane Post. Image courtesy of Hedgerow Exclusive Properties"},
  {
    outlet: "Behind The Hedges",
    title: "Backyard Bliss Becomes Big Return on the East End",
    date: "2024-05-21",
    dateText: "May 21, 2024",
    role: "Quoted",
    summary: "East End agents on how gardens and outdoor living add value, with Barry among those quoted.",
    url: "https://behindthehedges.com/backyard-bliss-becomes-big-return-east-end/",
  },
];

/** Every item on Hedgerow's press page (excluding the one already in Featured), newest first. */
export const hedgerowPress: PressItem[] = [
  {"outlet": "Mansion Global", "title": "$85 Million Hamptons Home With Ties to F. Scott Fitzgerald and Jackie Kennedy Finds a Buyer", "date": "2026-01", "dateText": "January 2026", "summary": "Dune Cottage in East Hampton Village, once asking $120M, finds a buyer after a price cut of almost 30%.", "url": "https://www.mansionglobal.com/amp/articles/85-million-hamptons-home-with-ties-to-f-scott-fitzgerald-and-jackie-kennedy-finds-a-buyer-143ac1ca", "image": "/images/press/hedgerow/85-milliom-hamptons-home-with-ties-to-f-scott-fitgerald-and.webp", "alt": "$85 Million Hamptons Home With Ties to F. Scott Fitzgerald and Jackie Kennedy Finds a Buyer, Mansion Global. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Real Deal", "title": "The 10 Priciest Residential Deals in the Hamptons in 2025", "date": "2025-12", "dateText": "December 2025", "summary": "The Hamptons' ten largest closings of 2025 total $579M, led by the first nine-figure deal since 2023.", "url": "https://therealdeal.com/new-york/tristate/2025/12/02/the-10-priciest-residential-deals-in-the-hamptons-in-2025/", "image": "/images/press/hedgerow/the-10-priciest-residential-deals-in-the-hamptons-in-2025.webp", "alt": "The 10 Priciest Residential Deals in the Hamptons in 2025, The Real Deal. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Real Deal", "title": "Boston Celtics co-owner buys Bridgehampton mansion for $58M", "date": "2025-11", "dateText": "November 2025", "summary": "Wyc Grousbeck and Emilia Fazzalari buy the new oceanfront at 165 Surfside Drive in Bridgehampton for $58M.", "url": "https://therealdeal.com/new-york/tristate/2025/11/19/boston-celtics-co-owner-buys-bridgehampton-mansion/", "image": "/images/press/hedgerow/boston-celtics-co-owner-buys-bridgehampton-mansion-for-58m.webp", "alt": "Boston Celtics co-owner buys Bridgehampton mansion for $58M, The Real Deal. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "Galerie", "title": "A Sag Harbor Home Frequented by Truman Capote Hits the Market for $16.5 Million", "date": "2025-10", "dateText": "October 2025", "summary": "An 1841 house at 207 Madison Street in Sag Harbor Village, once a Truman Capote refuge, lists for $16.5M.", "url": "https://galeriemagazine.com/sag-harbor-home-frequented-by-truman-capote-hits-the-market/", "image": "/images/press/hedgerow/a-sag-harbor-home-frequented-by-truman-capote-hits-the-marke.webp", "alt": "A Sag Harbor Home Frequented by Truman Capote Hits the Market for $16.5 Million, Galerie. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "New York Post", "title": "Truman Capote Often Visited This $16.49M Hamptons Home, Which Features His Red Mustang For an Extra Price", "date": "2025-10", "dateText": "October 2025", "summary": "The Capote-linked Sag Harbor house lists for $16.49M after a full renovation, with his red Mustang offered separately.", "url": "https://nypost.com/2025/10/07/real-estate/truman-capote-frequented-this-listed-16-49m-sag-harbor-home/", "image": "/images/press/hedgerow/truman-capote-often-visited-this-16-49m-hamptons-home-which.webp", "alt": "Truman Capote Often Visited This $16.49M Hamptons Home, Which Features His Red Mustang For an Extra Price, New York Post. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Wall Street Journal", "title": "The Hamptons Luxury Housing Market Is Staging a Comeback for the Ages", "date": "2025-10", "dateText": "October 2025", "summary": "Sales above $10M on the East End surge past even pandemic-era levels.", "url": "https://www.wsj.com/real-estate/luxury-homes/hamptons-luxury-housing-market-comeback-05ddf690?gaa_at=eafs&gaa_n=AWEtsqfJNUbHwO3FLq_2qDDPB53T_Mimk0SjVthmhyxZBXANDukNfCR55CSaDUe3Px4%3D&gaa_ts=695bef13&gaa_sig=xqc52wSBHvvvhG6PV2nToivs5iBckRUzfjvrLnv_Q7RRZWaJEy0aIGG60Gsg3gPr7suh1QLYgmYqlGlWV0cXJA%3D%3D", "image": "/images/press/hedgerow/the-hamptons-luxury-housing-market-is-staging-a-comeback-for.webp", "alt": "The Hamptons Luxury Housing Market Is Staging a Comeback for the Ages, The Wall Street Journal. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Real Deal", "title": "Fashion Designer Lists Hamptons Home For $50M", "date": "2025-09", "dateText": "September 2025", "summary": "Reed Krakoff's glass-pavilion oceanfront in Amagansett comes to market at $49.5M, with Hedgerow holding the listing.", "url": "https://therealdeal.com/new-york/tristate/2025/09/08/fashion-designer-desires-50m-for-hamptons-home/", "image": "/images/press/hedgerow/fashion-designer-lists-hamptons-home-for-50m.webp", "alt": "Fashion Designer Lists Hamptons Home For $50M, The Real Deal. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "New York Post", "title": "Fashion Titan Reed Krakoff Asks $49.5M For His Glassy Oceanfront Hamptons Estate", "date": "2025-09", "dateText": "September 2025", "summary": "Reed Krakoff lists his 7,200-square-foot Amagansett house, with 200 feet on the ocean, for $49.5M.", "url": "https://nypost.com/2025/09/05/real-estate/reed-krakoff-wants-49-5m-for-his-glassy-hamptons-home/", "image": "/images/press/hedgerow/fashion-titan-reed-krakoff-asks-49-5m-for-his-glassy-oceanfr.webp", "alt": "Fashion Titan Reed Krakoff Asks $49.5M For His Glassy Oceanfront Hamptons Estate, New York Post. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Real Deal", "title": "Video Game Mogul Drops $32M on East Hampton Oceanfront Estate", "date": "2025-09", "dateText": "September 2025", "summary": "Saber Interactive co-founder Matthew Karch buys an East Hampton Village oceanfront on Lily Pond Lane.", "url": "https://therealdeal.com/new-york/tristate/2025/09/12/video-game-mogul-drops-32m-on-east-hampton-oceanfront/", "image": "/images/press/hedgerow/video-game-mogul-drops-32m-on-east-hampton-oceanfront-estate.webp", "alt": "Video Game Mogul Drops $32M on East Hampton Oceanfront Estate, The Real Deal. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "Behind The Hedges", "title": "Oceanfront East Hampton Estate on Lily Pond Lane Has Found a Buyer", "date": "2025-08", "dateText": "August 2025", "summary": "33 Lily Pond Lane, an East Hampton Village oceanfront last asking $39M, goes into contract.", "url": "https://behindthehedges.com/east-hampton-estate-lily-pond-lane-buyer/", "image": "/images/press/hedgerow/oceanfront-east-hampton-estate-on-lily-pond-lane-has-found-a.webp", "alt": "Oceanfront East Hampton Estate on Lily Pond Lane Has Found a Buyer, Behind The Hedges. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Real Deal", "title": "Hamptons’ Top Brokerages Navigate Dragging Market, Uptick in Competition", "date": "2025-08", "dateText": "August 2025", "summary": "The Real Deal's annual look at the Hamptons' leading brokerages in a year slowed by tariffs and rates.", "url": "https://therealdeal.com/magazine/august-2025/hamptons-top-brokerages/", "image": "/images/press/hedgerow/hamptons-top-brokerages-navigate-dragging-market-uptick-in-c.webp", "alt": "Hamptons’ Top Brokerages Navigate Dragging Market, Uptick in Competition, The Real Deal. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Real Deal", "title": "In the Hamptons, Rental Seasonality is Dead and Big-Ticket Trades Are Back", "date": "2025-06", "dateText": "June 2025", "summary": "East End brokers report big-ticket trades returning and rentals moving year-round despite tariff uncertainty.", "url": "https://therealdeal.com/magazine/june-2025/hamptons-rising/", "image": "/images/press/hedgerow/in-the-hamptons-rental-seasonality-is-dead-and-big-ticket-tr.webp", "alt": "In the Hamptons, Rental Seasonality is Dead and Big-Ticket Trades Are Back, The Real Deal. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "Behind The Hedges", "title": "Bridgehampton Oceanfront Estate From “Wall Street” Sold", "date": "2025-05", "dateText": "May 2025", "summary": "67 Surfside Drive, the Bridgehampton oceanfront seen as Gordon Gekko's house in Wall Street, closes at $32M.", "url": "https://behindthehedges.com/bridgehampton-oceanfront-wall-street-sold/", "image": "/images/press/hedgerow/bridgehampton-oceanfront-estate-from-wall-street-sold.webp", "alt": "Bridgehampton Oceanfront Estate From “Wall Street” Sold, Behind The Hedges. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Real Deal", "title": "East Hampton Estate Hits Market For $42M", "date": "2025-04", "dateText": "April 2025", "summary": "The late McKinsey executive Robert O'Block's compound at 24 and 36 Jeffreys Lane in East Hampton comes to market.", "url": "https://therealdeal.com/new-york/tristate/2025/04/18/east-hampton-estate-hits-market-for-42m/", "image": "/images/press/hedgerow/east-hampton-estate-hits-market-for-42m.webp", "alt": "East Hampton Estate Hits Market For $42M, The Real Deal. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Hollywood Reporter", "title": "Who’s Buying What in the Big Apple? Ask NYC’s Top Realtors", "date": "2025-04", "dateText": "April 2025", "summary": "New York's top brokers on how buyers moved through tariff volatility, tight inventory, and high rates in 2025.", "url": "https://www.hollywoodreporter.com/lifestyle/real-estate/top-new-york-real-estate-agents-2025-1236191392/", "image": "/images/press/hedgerow/whos-buying-what-in-the-big-apple-ask-nycs-top-realtors.webp", "alt": "Who’s Buying What in the Big Apple? Ask NYC’s Top Realtors, The Hollywood Reporter. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Hollywood Reporter", "title": "The Hollywood Reporter Announces New York Power Broker Awards Nominees, Eleonora Srugo and Steve Gold to Host", "date": "2025-04", "dateText": "April 2025", "summary": "Nominees are announced for The Hollywood Reporter's fourth annual New York Power Broker Awards.", "url": "https://www.hollywoodreporter.com/lifestyle/real-estate/new-york-power-broker-awards-nominees-eleonora-srugo-1236182124/", "image": "/images/press/hedgerow/the-hollywood-reporter-announces-new-york-power-broker-award.webp", "alt": "The Hollywood Reporter Announces New York Power Broker Awards Nominees, Eleonora Srugo and Steve Gold to Host, The Hollywood Reporter. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Wall Street Journal", "title": "Late McKinsey Exec’s East Hampton Compound Lists for $41.9 Million", "date": "2025-04", "dateText": "April 2025", "summary": "The East Hampton compound of the late McKinsey executive Robert O'Block lists for $41.9M.", "url": "https://www.wsj.com/real-estate/luxury-homes/mckinsey-executive-east-hampton-ny-compound-48c3c8ae?gaa_at=eafs&gaa_n=AWEtsqeNTqBN95HWwHW_craVMbDAS1L3mnybM8hWPYar8a0kRvN59f0zLwwD-8A48-Y%3D&gaa_ts=6967df98&gaa_sig=2dgkGlfx94IOeaXvjrmzoS5KBTBGdd-9tfucSl6RndFxR51RhZz04X67tjkl86edjfmIWm_kAXcPICLEk36L8w%3D%3D", "image": "/images/press/hedgerow/late-mckinsey-execs-east-hampton-compound-lists-for-41-9-mil.webp", "alt": "Late McKinsey Exec’s East Hampton Compound Lists for $41.9 Million, The Wall Street Journal. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "Cottages & Gardens", "title": "Tour a Waterfront East Hampton Estate Once Owned by Lee Radziwill and Asking $95M", "date": "2025-01", "dateText": "January 2025", "summary": "A tour of Dune Cottage, the East Hampton waterfront estate once owned by Lee Radziwill, asking $95M.", "url": "https://cottagesgardens.com/tour-a-waterfront-east-hampton-estate-once-owned-by-lee-radziwill-and-asking-95m/", "image": "/images/press/hedgerow/tour-a-waterfront-east-hampton-estate-once-owned-by-lee-radz.webp", "alt": "Tour a Waterfront East Hampton Estate Once Owned by Lee Radziwill and Asking $95M, Cottages & Gardens. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "Robb Report", "title": "This $19 Million Hamptons Estate Is a One-Acre Manicured Paradise", "date": "2025-01", "dateText": "January 2025", "summary": "A Matthews Lane estate in Bridgehampton, set on one manicured acre, lists for $19M.", "url": "https://robbreport.com/shelter/homes-for-sale/matthews-lane-bridgehampton-new-york-1236177074/", "image": "/images/press/hedgerow/this-19-million-hamptons-estate-is-a-one-acre-manicured-para.webp", "alt": "This $19 Million Hamptons Estate Is a One-Acre Manicured Paradise, Robb Report. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "Forbes", "title": "Behind Hedgerow, The New And Exclusive Hamptons Real Estate Firm", "date": "2024-12", "dateText": "December 2024", "summary": "A profile of Hedgerow, founded in 2020 by Gary Cooper and Preston Kaye, and its rise in the ultra-luxury Hamptons market.", "url": "https://www.forbes.com/sites/emmareynolds/2024/12/19/behind-hedgerow-the-most-exclusive-hamptons-real-estate-firm/", "image": "/images/press/hedgerow/behind-hedgerow-the-new-and-exclusive-hamptons-real-estate-f.webp", "alt": "Behind Hedgerow, The New And Exclusive Hamptons Real Estate Firm, Forbes. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Real Deal", "title": "Hamptons’ legacy residential brokerages hang on to the top", "date": "2024-08", "dateText": "August 2024", "summary": "The Real Deal ranks Hamptons brokerages as legacy firms hold the top spots and newer firms gain ground.", "url": "https://therealdeal.com/magazine/august-2024/hamptonss-legacy-residential-brokerages-hang-on-to-the-top/", "image": "/images/press/hedgerow/hamptons-legacy-residential-brokerages-hang-on-to-the-top.webp", "alt": "Hamptons’ legacy residential brokerages hang on to the top, The Real Deal. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "Vogue", "title": "Naomi Watts, Camila Morrone, and More Joined Chef Francis Mallmann’s Hamptons Summer Barbecue", "date": "2024-07", "dateText": "July 2024", "summary": "Dom Pérignon's summer dinner, cooked by chef Francis Mallmann, at a waterfront residence in Water Mill.", "url": "https://www.vogue.com/slideshow/dom-perignon-chef-francis-mallman-dinner-party-2024", "image": "/images/press/hedgerow/naomi-watts-camila-morrone-and-more-joined-chef-francis-mall.webp", "alt": "Naomi Watts, Camila Morrone, and More Joined Chef Francis Mallmann’s Hamptons Summer Barbecue, Vogue. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "Entrepreneur", "title": "Dom Pérignon Hosts First-Ever Public Ticketed Event for $3,000 a Person at Lavish $99 Million Hamptons Estate", "date": "2024-07", "dateText": "July 2024", "summary": "Dom Pérignon's first public ticketed dinner, at $3,000 a seat, held at a $99M estate in Water Mill.", "url": "https://www.entrepreneur.com/business-news/dom-perignon-hosts-lavish-dinner-at-99-million-estate/477428", "image": "/images/press/hedgerow/dom-perignon-hosts-first-ever-public-ticketed-event-for-3000.webp", "alt": "Dom Pérignon Hosts First-Ever Public Ticketed Event for $3,000 a Person at Lavish $99 Million Hamptons Estate, Entrepreneur. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "Behind The Hedges", "title": "Crème de la Crème of Luxury Real Estate: The Top 10 Priciest Properties in the Hamptons", "date": "2024-07", "dateText": "July 2024", "summary": "The ten most expensive Hamptons listings of summer 2024, every one of them on the water.", "url": "https://behindthehedges.com/top-10-priciest-properties-the-hamptons-2024/", "image": "/images/press/hedgerow/creme-de-la-creme-of-luxury-real-estate-the-top-10-priciest.webp", "alt": "Crème de la Crème of Luxury Real Estate: The Top 10 Priciest Properties in the Hamptons, Behind The Hedges. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "New York Post", "title": "On Shelter Island, a rare waterfront home owned by the same family for generations lists for $5.45M", "date": "2024-07", "dateText": "July 2024", "summary": "20 Prospect Avenue, an 1883 house in Shelter Island Heights held by one family for generations, lists for $5.45M.", "url": "https://nypost.com/2024/07/17/real-estate/shelter-island-home-in-same-family-for-generations-wants-5-45m/", "image": "/images/press/hedgerow/on-shelter-island-a-rare-waterfront-home-owned-by-the-same-f.webp", "alt": "On Shelter Island, a rare waterfront home owned by the same family for generations lists for $5.45M, New York Post. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Real Deal", "title": "Bucking the old guard: Hamptons brokers answer questions about staying power", "date": "2024-07", "dateText": "July 2024", "summary": "Newer Hamptons brokers on building staying power against the established firms.", "url": "https://therealdeal.com/magazine/july-2024/bucking-the-old-guard-hamptons-brokers-answer-questions-about-staying-power/", "image": "/images/press/hedgerow/bucking-the-old-guard-hamptons-brokers-answer-questions-abou.webp", "alt": "Bucking the old guard: Hamptons brokers answer questions about staying power, The Real Deal. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Wall Street Journal", "title": "Asking $120 Million: An Oceanfront Estate Near One of the Hamptons’ Most Expensive Streets", "date": "2024-06", "dateText": "June 2024", "summary": "Ann Tenenbaum lists the East Hampton oceanfront estate she twice rebuilt with Thomas H. Lee for $120M.", "url": "https://www.wsj.com/real-estate/luxury-homes/hamptons-estate-lists-for-120-million-82a1e050", "image": "/images/press/hedgerow/asking-120-million-an-oceanfront-estate-near-one-of-the-hamp.webp", "alt": "Asking $120 Million: An Oceanfront Estate Near One of the Hamptons’ Most Expensive Streets, The Wall Street Journal. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "New York Post", "title": "The Most Gorgeously Designed Hamptons Home Rentals For 2024", "date": "2024-05", "dateText": "May 2024", "summary": "The season's best-designed Hamptons rentals, including 26 Harbor Drive in Sag Harbor.", "url": "https://nypost.com/2024/05/23/real-estate/the-priciest-summer-rentals-in-the-hamptons-are-worth-it/", "image": "/images/press/hedgerow/the-most-gorgeously-designed-hamptons-home-rentals-for-2024.webp", "alt": "The Most Gorgeously Designed Hamptons Home Rentals For 2024, New York Post. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "Robb Report", "title": "Two Restored Barns Add to the Bucolic Charm of This $12.5 Million Hamptons Farmhouse", "date": "2024-04-08", "dateText": "April 8, 2024", "summary": "A $12.5M farmhouse at 453 Hedges Lane in Sagaponack, with two restored barns.", "url": "https://robbreport.com/shelter/homes-for-sale/new-york-hamptons-453-hedges-lane-sagaponack-1235572790/", "image": "/images/press/hedgerow/two-restored-barns-add-to-the-bucolic-charm-of-this-12-5-mil.webp", "alt": "Two Restored Barns Add to the Bucolic Charm of This $12.5 Million Hamptons Farmhouse, Robb Report. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "New York Post", "title": "A Hamptons compound that sold for a near-record $118.5M in 2021 seeks a new owner for $99.5M", "date": "2024-04-01", "dateText": "April 1, 2024", "summary": "70 and 71 Cobb Lane, a 21-acre Water Mill compound on Mecox Bay that sold for $118.5M, lists for $99.5M.", "url": "https://nypost.com/2024/04/01/real-estate/hamptons-compound-that-sold-for-118-5m-in-2021-asks-99-5m/", "image": "/images/press/hedgerow/a-hamptons-compound-that-sold-for-a-near-record-118-5m-in-20.webp", "alt": "A Hamptons compound that sold for a near-record $118.5M in 2021 seeks a new owner for $99.5M, New York Post. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Wall Street Journal", "title": "They Love Their $14.95 Million Hamptons House. The Problem? Their Dog Hates It.", "date": "2024-04", "dateText": "April 2024", "summary": "A Sag Harbor couple lists their $14.95M house because their goldendoodle never took to it.", "url": "https://www.wsj.com/real-estate/luxury-homes/they-love-their-14-95-million-hamptons-house-the-problem-their-dog-hates-it-0cd7e13b", "image": "/images/press/hedgerow/they-love-their-14-95-million-hamptons-house-the-problem-the.webp", "alt": "They Love Their $14.95 Million Hamptons House. The Problem? Their Dog Hates It., The Wall Street Journal. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "New York Post", "title": "This Hamptons compound has rented for a cool $1.5M for the summer season", "date": "2024-03-28", "dateText": "March 28, 2024", "summary": "Leon Wagner's Sagaponack compound rents for just over $1.5M for the summer.", "url": "https://nypost.com/2024/03/28/real-estate/hamptons-compound-rents-for-a-cool-1-5m-for-the-summer/", "image": "/images/press/hedgerow/this-hamptons-compound-has-rented-for-a-cool-1-5m-for-the-su.webp", "alt": "This Hamptons compound has rented for a cool $1.5M for the summer season, New York Post. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Real Deal", "title": "Hamptons brokerages: The empires out East", "date": "2023-08-01", "dateText": "August 1, 2023", "summary": "The Real Deal's 2023 ranking of the Hamptons brokerages after a two-speed 2022.", "url": "https://therealdeal.com/magazine/national-august-2023/hamptons-brokerages-the-empires-out-east/", "image": "/images/press/hedgerow/hamptons-brokerages-the-empires-out-east.webp", "alt": "Hamptons brokerages: The empires out East, The Real Deal. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Hollywood Reporter", "title": "New York’s Top Real Estate Agents: The 2023 List", "date": "2023-06-27", "dateText": "June 27, 2023", "summary": "The Hollywood Reporter's 2023 list of New York's top real estate agents.", "url": "https://www.hollywoodreporter.com/lifestyle/real-estate/new-york-top-real-estate-agents-2023-1235519825/", "image": "/images/press/hedgerow/new-yorks-top-real-estate-agents-the-2023-list.webp", "alt": "New York’s Top Real Estate Agents: The 2023 List, The Hollywood Reporter. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "Architectural Digest", "title": "The Most Expensive Hamptons Rental Is Going for $1 Million per Month", "date": "2023-06-05", "dateText": "June 5, 2023", "summary": "70 Cobb Lane in Water Mill asks $1M a month, the summer's priciest Hamptons rental.", "url": "https://www.architecturaldigest.com/story/the-most-expensive-hamptons-rental-is-going-for-1-million-per-month", "image": "/images/press/hedgerow/the-most-expensive-hamptons-rental-is-going-for-1-million-pe.webp", "alt": "The Most Expensive Hamptons Rental Is Going for $1 Million per Month, Architectural Digest. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "Robb Report", "title": "This Modern $16 Million Hamptons Home Once Starred in ‘Billions.’ Now It’s up for Grabs.", "date": "2023-06", "dateText": "June 2023", "summary": "A $16M Bridgehampton modern that appeared on Showtime's Billions comes to market.", "url": "https://robbreport.com/shelter/homes-for-sale/billions-bridgehampton-home-1234853393/", "image": "/images/press/hedgerow/this-modern-16-million-hamptons-home-once-starred-in-billion.webp", "alt": "This Modern $16 Million Hamptons Home Once Starred in ‘Billions.’ Now It’s up for Grabs., Robb Report. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "Mansion Global", "title": "A $27.5 Million Hamptons Estate That Includes a 19th-Century Schoolhouse", "date": "2023-04-21", "dateText": "April 21, 2023", "summary": "A $27.5M Sagaponack new build on three acres that includes the original 1884 schoolhouse.", "url": "https://www.mansionglobal.com/articles/a-27-5-million-hamptons-estate-that-includes-a-19th-century-schoolhouse-33299fd5", "image": "/images/press/hedgerow/a-27-5-million-hamptons-estate-that-includes-a-19th-century.webp", "alt": "A $27.5 Million Hamptons Estate That Includes a 19th-Century Schoolhouse, Mansion Global. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "New York Post", "title": "This is the priciest-ever Hamptons summer rental", "date": "2023-04-10", "dateText": "April 10, 2023", "summary": "A 12.2-acre Mecox Bay peninsula in Water Mill asks $2.5M for the summer, a record Hamptons rental ask.", "url": "https://nypost.com/2023/04/10/this-is-the-priciest-ever-hamptons-summer-rental/", "image": "/images/press/hedgerow/this-is-the-priciest-ever-hamptons-summer-rental.webp", "alt": "This is the priciest-ever Hamptons summer rental, New York Post. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "Robb Report", "title": "This $60 Million Hamptons Estate Comes With a 750-Gallon Shark Tank", "date": "2023-04-06", "dateText": "April 6, 2023", "summary": "A Water Mill estate with a 750-gallon indoor shark tank lists for $59.5M.", "url": "https://robbreport.com/shelter/homes-for-sale/hamptons-home-shark-tank-1234827567/", "image": "/images/press/hedgerow/this-60-million-hamptons-estate-comes-with-a-750-gallon-shar.webp", "alt": "This $60 Million Hamptons Estate Comes With a 750-Gallon Shark Tank, Robb Report. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Wall Street Journal", "title": "Oceanfront Hamptons Home Sells for Close to $35 Million", "date": "2023-02-07", "dateText": "February 7, 2023", "summary": "James Carney sells his Dune Road oceanfront in Bridgehampton off-market for close to $35M.", "url": "https://www.wsj.com/articles/oceanfront-hamptons-home-sells-for-close-to-35-million-11675798172", "image": "/images/press/hedgerow/oceanfront-hamptons-home-sells-for-close-to-35-million.webp", "alt": "Oceanfront Hamptons Home Sells for Close to $35 Million, The Wall Street Journal. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Wall Street Journal", "title": "Larry Ellison, Ken Griffin and Other Rich Buyers Kept the Luxury Market ‘Separated From Reality’ in 2022", "date": "2023-01", "dateText": "January 2023", "summary": "The biggest luxury deals of 2022 in the U.S., with at least seven closing at $100M or more.", "url": "https://www.wsj.com/articles/biggest-real-estate-deals-2022-11672774573", "image": "/images/press/hedgerow/larry-ellison-ken-griffin-and-other-rich-buyers-kept-the-lux.webp", "alt": "Larry Ellison, Ken Griffin and Other Rich Buyers Kept the Luxury Market ‘Separated From Reality’ in 2022, The Wall Street Journal. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Real Deal", "title": "Divorce lawyer sells Bridgehampton home for $45M", "date": "2022-08-04", "dateText": "August 4, 2022", "summary": "Irving Shafran sells his five-acre Bridgehampton property for about $45M.", "url": "https://therealdeal.com/new-york/tristate/2022/08/04/divorce-lawyer-sells-bridgehampton-home-for-45m/", "image": "/images/press/hedgerow/divorce-lawyer-sells-bridgehampton-home-for-45m.webp", "alt": "Divorce lawyer sells Bridgehampton home for $45M, The Real Deal. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Real Deal", "title": "Hedgerow Has Carved Out Its Niche by Zeroing In on Ultra-Luxury Properties", "date": "2022-08-02", "dateText": "August 2, 2022", "summary": "How Hedgerow carved out its niche by focusing on ultra-luxury properties.", "url": "https://therealdeal.com/magazine/national-august-2022/inflation-hedge/", "image": "/images/press/hedgerow/luxury-brokerage-hedgerow-faces-its-toughest-challenge-yet.webp", "alt": "Hedgerow Has Carved Out Its Niche by Zeroing In on Ultra-Luxury Properties, The Real Deal. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Wall Street Journal", "title": "A Hamptons Home Sells for Roughly $45 Million", "date": "2022-08-02", "dateText": "August 2, 2022", "summary": "A roughly five-acre Bridgehampton property sells off-market for about $45M.", "url": "https://www.wsj.com/articles/a-hamptons-home-sells-for-roughly-45-million-11659453233", "image": "/images/press/hedgerow/a-hamptons-home-sells-for-roughly-45-million.webp", "alt": "A Hamptons Home Sells for Roughly $45 Million, The Wall Street Journal. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "New York Post", "title": "NBA star Kevin Love and model Kate Bock put Hamptons house up for rent", "date": "2022-05-24", "dateText": "May 24, 2022", "summary": "Kevin Love and Kate Bock offer their Hamptons house for summer rent.", "url": "https://nypost.com/2022/05/24/kevin-love-and-kate-bock-put-their-hamptons-home-up-for-rent/", "image": "/images/press/hedgerow/nba-star-kevin-love-and-model-kate-bock-put-hamptons-house-u.webp", "alt": "NBA star Kevin Love and model Kate Bock put Hamptons house up for rent, New York Post. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "Mansion Global", "title": "In the Hamptons, a $48 Million Home Sells Before It Hits the Market", "date": "2022-05-17", "dateText": "May 17, 2022", "summary": "The late Johnson & Johnson chief James Burke's Sagaponack oceanfront sells near its $48M ask before reaching the market.", "url": "https://www.mansionglobal.com/articles/in-the-hamptons-a-48-million-home-sells-before-it-hits-the-market-01652797178", "image": "/images/press/hedgerow/in-the-hamptons-a-48-million-home-sells-before-it-hits-the-m.webp", "alt": "In the Hamptons, a $48 Million Home Sells Before It Hits the Market, Mansion Global. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Wall Street Journal", "title": "In the Hamptons, a $48 Million Home Sells Before It Hits the Market", "date": "2022-05-16", "dateText": "May 16, 2022", "summary": "James Burke's former Sagaponack oceanfront trades off-market close to its $48M asking price.", "url": "https://www.wsj.com/articles/in-the-hamptons-a-48-million-home-sells-before-it-hits-the-market-11652737587?st=1ewld5192x4qzcz&reflink=article_email_share", "image": "/images/press/hedgerow/in-the-hamptons-a-48-million-home-sells-before-it-hits-the-m.webp", "alt": "In the Hamptons, a $48 Million Home Sells Before It Hits the Market, The Wall Street Journal. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "Mansion Global", "title": "A Sprawling $72 Million Waterfront Hamptons Estate Is Headed to the Market", "date": "2022-05-02", "dateText": "May 2, 2022", "summary": "A 9-acre Water Mill waterfront estate, part of 2021's largest Hamptons deal, comes to market at $72M.", "url": "https://www.mansionglobal.com/amp/articles/a-sprawling-72-million-waterfront-hamptons-estate-is-headed-to-the-market-01651505716", "image": "/images/press/hedgerow/a-sprawling-72-million-waterfront-hamptons-estate-is-headed.webp", "alt": "A Sprawling $72 Million Waterfront Hamptons Estate Is Headed to the Market, Mansion Global. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "New York Post", "title": "Billionaire’s Row penthouse sells for $70.5M in biggest deal of the year", "date": "2022-04-26", "dateText": "April 26, 2022", "summary": "An 82nd-floor condo at 432 Park Avenue sells for $70.5M, the city's largest deal of the year at the time.", "url": "https://nypost.com/2022/04/26/billionaires-row-penthouse-sells-for-70m/", "image": "/images/press/hedgerow/billionaires-row-penthouse-sells-for-70-5m-%e2%81%a0in-bigge.webp", "alt": "Billionaire’s Row penthouse sells for $70.5M in biggest deal of the year, New York Post. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Wall Street Journal", "title": "Condo at New York’s 432 Park Avenue in Contract to Sell for Roughly $70 Million", "date": "2022-04-18", "dateText": "April 18, 2022", "summary": "An 82nd-floor unit at 432 Park Avenue goes into contract at about $70M after nearly two years on the market.", "url": "https://www.wsj.com/articles/condo-at-new-yorks-432-park-avenue-in-contract-to-sell-for-roughly-70-million-11650315384", "image": "/images/press/hedgerow/condo-at-new-yorks-432-park-avenue-in-contract-to-sell-for-r.webp", "alt": "Condo at New York’s 432 Park Avenue in Contract to Sell for Roughly $70 Million, The Wall Street Journal. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "New York Post", "title": "Want a Splashy Hamptons Spread this Summer? Get Ready to Drop $1M", "date": "2022-03", "dateText": "March 2022", "summary": "Top Hamptons summer rentals approach $1M as owners stay put and inventory tightens.", "url": "https://nypost.com/2022/03/31/a-hamptons-rental-could-set-you-back-1m-this-summer/", "image": "/images/press/hedgerow/want-a-splashy-hamptons-spread-this-summer-get-ready-to-drop.webp", "alt": "Want a Splashy Hamptons Spread this Summer? Get Ready to Drop $1M, New York Post. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "Behind The Hedges", "title": "Exclusive North Haven Estate Sells at Over Asking Price", "date": "2022-03", "dateText": "March 2022", "summary": "A North Haven estate sells above its asking price.", "url": "https://behindthehedges.com/exclusive-north-haven-estate-sells-over-asking/", "image": "/images/press/hedgerow/exclusive-north-haven-estate-sells-at-over-asking-price.webp", "alt": "Exclusive North Haven Estate Sells at Over Asking Price, Behind The Hedges. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "Mansion Global", "title": "Bidding War Over $17 Million Gated Hamptons Beach Estate Highlights Fierce Luxury Market", "date": "2022-03", "dateText": "March 2022", "summary": "A gated Sag Harbor waterfront listed at $16.95M sells for $17M after a bidding war.", "url": "https://www.mansionglobal.com/articles/bidding-war-over-17-million-gated-hamptons-beach-estate-highlights-fierce-luxury-market-01646696139", "image": "/images/press/hedgerow/bidding-war-over-17-million-gated-hamptons-beach-estate-high.webp", "alt": "Bidding War Over $17 Million Gated Hamptons Beach Estate Highlights Fierce Luxury Market, Mansion Global. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Real Deal", "title": "Southampton Compound Sells for $118.5M", "date": "2022-01-28", "dateText": "January 28, 2022", "summary": "Arthur and Jason Rabin sell their Water Mill compound off-market for $118.5M, topping 2021's largest Hamptons sale.", "url": "https://therealdeal.com/tristate/2022/01/28/southampton-compound-sells-for-118-5m/", "image": "/images/press/hedgerow/southampton-compound-sells-for-118-5m.webp", "alt": "Southampton Compound Sells for $118.5M, The Real Deal. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Real Deal", "title": "Peloton CEO is buyer of $55M East Hampton estate", "date": "2021-12-17", "dateText": "December 17, 2021", "summary": "Peloton CEO John Foley is the buyer of 442 Further Lane in East Hampton at $55M.", "url": "https://therealdeal.com/tristate/2021/12/17/peloton-ceo-is-buyer-of-55m-east-hampton-estate/", "image": "/images/press/hedgerow/peloton-ceo-is-buyer-of-55m-east-hampton-estate.webp", "alt": "Peloton CEO is buyer of $55M East Hampton estate, The Real Deal. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "Forbes", "title": "Peloton CEO Buys $55 Million Hamptons Estate, Despite Company’s Plummeting Share Prices", "date": "2021-12-17", "dateText": "December 17, 2021", "summary": "John Foley buys 442 Further Lane in East Hampton, a Hedgerow listing, for $55M.", "url": "https://www.forbes.com/sites/emmareynolds/2021/12/17/peloton-ceo-buys-55-million-hamptons-estate-despite-companys-plummeting-share-prices/?sh=529e57ae4a1e", "image": "/images/press/hedgerow/peloton-ceo-buys-55-million-hamptons-estate-despite-companys.webp", "alt": "Peloton CEO Buys $55 Million Hamptons Estate, Despite Company’s Plummeting Share Prices, Forbes. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "Mansion Global", "title": "East Hampton Mansion With 400 Feet of Ocean Frontage Sells for $55 Million", "date": "2021-12-03", "dateText": "December 3, 2021", "summary": "An East Hampton oceanfront with about 400 feet of frontage sells for $55M, above its $52.5M ask.", "url": "https://www.mansionglobal.com/articles/east-hampton-mansion-with-400-feet-of-ocean-frontage-sells-for-55-million-01638563594", "image": "/images/press/hedgerow/east-hampton-mansion-with-400-feet-of-ocean-frontage-sells-f.webp", "alt": "East Hampton Mansion With 400 Feet of Ocean Frontage Sells for $55 Million, Mansion Global. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Real Deal", "title": "East Hampton estate sells above $52M ask in 1 month", "date": "2021-09-10", "dateText": "September 10, 2021", "summary": "442 Further Lane in East Hampton goes into contract above its $52.5M ask within a month.", "url": "https://therealdeal.com/tristate/2021/09/10/east-hampton-estate-sells-above-52-5m-after-1-month-on-the-market/", "image": "/images/press/hedgerow/east-hampton-estate-sells-above-52m-ask-in-1-month.webp", "alt": "East Hampton estate sells above $52M ask in 1 month, The Real Deal. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Wall Street Journal", "title": "New England Patriots Owner Robert Kraft Buys Hamptons Beach House for $43 Million", "date": "2021-05-04", "dateText": "May 4, 2021", "summary": "Robert Kraft buys a Meadow Lane beach house in Southampton off-market for $43M.", "url": "https://www.wsj.com/articles/new-england-patriots-owner-robert-kraft-buys-hamptons-mansion-for-43-million-11620131170?mod=re_feat_strip_pos1", "image": "/images/press/hedgerow/new-england-patriots-owner-robert-kraft-buys-hamptons-beach.webp", "alt": "New England Patriots Owner Robert Kraft Buys Hamptons Beach House for $43 Million, The Wall Street Journal. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "27East", "title": "In-land Record Breaks As Southampton Village Racks Up Eight-Figure Real Estate Sales", "date": "2021-01-12", "dateText": "January 12, 2021", "summary": "55 Coopers Neck Lane in Southampton Village sells for $33.7M, possibly the highest price paid for an inland South Fork property.", "url": "https://www.27east.com/real-estate-news/in-land-record-breaks-as-southampton-village-racks-up-eight-figure-real-estate-sales-1749039/", "image": "/images/press/hedgerow/in-land-record-breaks-as-southampton-village-racks-up-eight.webp", "alt": "In-land Record Breaks As Southampton Village Racks Up Eight-Figure Real Estate Sales, 27East. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "The Real Deal", "title": "HFZ’s Ziel Feldman sells Hamptons home for $50M", "date": "2021-01-07", "dateText": "January 7, 2021", "summary": "Ziel Feldman sells 187 Dune Road in Bridgehampton off-market for $50M.", "url": "https://therealdeal.com/tristate/2021/01/07/hfzs-ziel-feldman-sells-hamptons-home-for-50m/", "image": "/images/press/hedgerow/hfzs-ziel-feldman-sells-hamptons-home-for-50m.webp", "alt": "HFZ’s Ziel Feldman sells Hamptons home for $50M, The Real Deal. Image courtesy of Hedgerow Exclusive Properties"},
  {"outlet": "Behind The Hedges", "title": "Oceanfront Bridgehampton Home With Storied Past Sells for $50 Million in Off-Market Deal", "date": "2021-01", "dateText": "January 2021", "summary": "187 Dune Road, a new Bridgehampton oceanfront, trades off-market for $50.15M, one of 2020's top Hamptons sales.", "url": "https://behindthehedges.com/oceanfront-bridgehampton-home-with-storied-past-sells-for-50-million-in-off-market-deal/", "image": "/images/press/hedgerow/oceanfront-bridgehampton-home-with-storied-past-sells-for-50.webp", "alt": "Oceanfront Bridgehampton Home With Storied Past Sells for $50 Million in Off-Market Deal, Behind The Hedges. Image courtesy of Hedgerow Exclusive Properties"},
];
